Enhancement | Add stylelint configuration
evergage/evergage-global-templates pull request #11
Opened 2020-08-14 20:10 UTC by amaskiellEG

# Description

Adds configuration for `stylelint`. All rules (including ordering) for the linter can be found in `.stylelintrc.json`

## Related Links
https://stylelint.io/user-guide/get-started
https://stylelint.io/user-guide/configure#rules
https://github.com/hudochenkov/stylelint-config-hudochenkov/blob/master/order.js

https://github.com/stylelint/stylelint
https://github.com/stylelint/stylelint-config-standard
https://github.com/hudochenkov/stylelint-order

## How to test
- run `npm i -g stylelint stylelint-config-standard stylelint-order`
- install the [`stylelint` VS Code extension](https://marketplace.visualstudio.com/items?itemName=stylelint.vscode-stylelint)
- add the following to `settings.json` in VS Code:
```
"editor.codeActionsOnSave": {
    "source.fixAll.styleLint": true
}
```
- view and save `.css` file for one of the templates
_(Note that since re-ordering CSS is not an auto-fixable problem in VS Code, it cannot be done on save. However, you should see that mis-ordered styles are underlined.)_

### TODOs
- update confluence doc with instructions (or should this be added to the [dev docs](https://developer.evergage.com/templates/templates-style-guide-and-coding-conventions)?)

2020-08-14 20:12 UTC, avkieu submitted a review, later dismissed

2020-09-09 01:03 UTC, nriserEG commented on .stylelintrc.json
> +				"vertical-align",
Remove vertical-align

2020-09-09 01:04 UTC, nriserEG commented on .stylelintrc.json
> +                "max-height",
Add "vertical-align" after "max-height"

2020-09-15 06:02 UTC, nriserEG commented on .stylelintrc.json
> +				"flex-wrap",
Change order to:
flex-wrap
flex-flow

2020-09-15 06:06 UTC, nriserEG commented on .stylelintrc.json
> +				"justify-self",
Change order to: 
justify-content
justify-items
justify-self
align-content
align-items
align-self

2020-09-17 14:41 UTC, amaskiellEG commented on .stylelintrc.json
> +                "color",
What about these is spaced incorrectly?

2020-09-17 14:41 UTC, amaskiellEG commented on .stylelintrc.json
> +                "transition",
What about these is spaced incorrectly?

2020-09-17 14:43 UTC, amaskiellEG commented on .stylelintrc.json
> +				"clear",
Any reason for that? Seems like it'd be better to have them _somewhere_ just so that they're placed consistently _if_ they get used, you know?

2020-09-17 14:43 UTC, amaskiellEG commented on .stylelintrc.json
> +				"visibility",
Any reason for that? Seems like it'd be better to have them _somewhere_ just so that they're placed consistently _if_ they get used, you know?

2020-09-17 14:44 UTC, amaskiellEG commented on .stylelintrc.json
> +				"clear",
See: https://github.com/evergage/evergage-global-templates/pull/11#discussion_r474374961

2020-09-17 14:45 UTC, amaskiellEG commented on .stylelintrc.json
> +				"visibility",
See: https://github.com/evergage/evergage-global-templates/pull/11#discussion_r474374961

2020-09-17 16:23 UTC, nriserEG commented on .stylelintrc.json
> +                "color",
This is how I see it:
<img width="736" alt="Screen Shot 2020-09-17 at 9 22 20 AM" src="https://user-images.githubusercontent.com/32201252/93499053-5ebf5800-f8c7-11ea-8eda-2b36e39681d2.png">

2020-09-17 16:23 UTC, nriserEG commented on .stylelintrc.json
> +                "transition",
@amaskiellEG This is what I see:
<img width="710" alt="Screen Shot 2020-09-17 at 9 22 25 AM" src="https://user-images.githubusercontent.com/32201252/93499098-71399180-f8c7-11ea-87df-f5fd4f7e427e.png">

2020-09-21 18:58 UTC, amaskiellEG commented on .stylelintrc.json
> +                "color",
That's so weird... it hadn't shown up like that in VS Code for me, but I just un-indented them and re-indented them, and now git seems to notice the changes 🙃  wonder if tabs were copied instead of spaces, somehow...
![Screen Shot 2020-09-21 at 2 47 54 PM](https://user-images.githubusercontent.com/50626880/93808071-83923300-fc19-11ea-9cdf-6fdf0c2ce852.png)

2020-09-26 00:18 UTC, nriserEG commented
@amaskiellEG Updates look good 👍 There's one thing I mentioned in my first comment that you may have missed -- Could you also add vendor-prefixed properties? Ones listed in http://shouldiprefix.com/, such as flexbox, grids, and columns.

2020-09-28 20:13 UTC, amaskiellEG commented
@nriserEG ohp, sorry; I definitely missed that last comment! I'll add those in<br>

2020-09-29 19:05 UTC, nriserEG approved these changes
Looks great @amaskiellEG! Approved!

Thanks again for looking into this. This will be a game-changer 👍

2020-10-26 21:34 UTC, nriserEG commented on .stylelintrc.json
> +	}
```suggestion
	},
	"files.trimTrailingWhitespace": true,
	"diffEditor.ignoreTrimWhitespace": false
```

2020-10-26 21:38 UTC, nriserEG commented on .stylelintrc.json
> +        "indentation": 4,
```suggestion
        "indentation": 4,
        "number-leading-zero": "never",
        "no-missing-end-of-source-newline": null,
        "declaration-empty-line-before": ["always", {
		"ignore": [
			"after-declaration",
			"first-nested"
		]
	}],
```

2020-10-26 22:02 UTC, nriserEG requested changes
@amaskiellEG As we discussed earlier,
- I added suggestions for adding extra rules that have been helpful for me in writing templates.
- We'll actually want to remove all the vendor prefixes. Sorry I made you add them earlier!

Also, minor detail but could you update the entire code from using tab indentation to spaces (4 spaces)?

2020-10-26 22:12 UTC, nriserEG commented on .stylelintrc.json
> +        "indentation": 4,
```suggestion
        "indentation": 4,
        "number-leading-zero": "never",
        "no-missing-end-of-source-newline": null,
	"declaration-empty-line-before": ["always", {
		"ignore": [
			"after-declaration",
			"first-nested"
		]
	}],
```

2020-10-27 19:17 UTC, amaskiellEG commented on .stylelintrc.json
> +        "indentation": 4,
Hmmm the `"first-nested"` line is being picked up by a linter, with the message:

&gt; Value is not accepted. Valid values: "after-comment", "after-declaration", "inside-single-line-block".

Do you see that as well?

2020-10-27 19:42 UTC, nriserEG commented on .stylelintrc.json
> +        "indentation": 4,
@amaskiellEG yeah, I saw that as well but didn't believe it was accurate, since "first-nested" is listed in their doc https://stylelint.io/user-guide/rules/declaration-empty-line-before#ignore-after-comment-after-declaration-first-nested-inside-single-line-block and adding that rule seems to work

2020-11-12 23:12 UTC, nriserEG approved these changes

2020-12-02 04:50 UTC, merged