EVG-12047 | Redirect
evergage/evergage-global-templates pull request #20
Opened 2020-09-25 20:12 UTC by amaskiellEG

# Description

Adds the Redirect Template (using [NTO](https://www.northerntrailoutfitters.com/default/homepage))

This Global Template redirects the current page to another page, according the provided URL.

## Related Issues/Tickets

JIRA: https://help.evergage.com/browse/EVG-12047

## How to test
The Template and Campaign can be tested on the homepage of [NTO](https://www.northerntrailoutfitters.com/default/homepage) by forcing the SDK URL for the `amask` dataset in `training`: https://cdn.evgnet.com/beacon/training/amask/scripts/evergage.min.js

- **Template name:** [EVG-12047] Global - Redirect
- **Campaign name:** [EVG-12047] Redirect Test - NTO Homepage

_Note: it's important to note that this Template should be tightly coupled with [updates to the Flicker Defender gear](https://help.evergage.com/browse/EVG-12209)._

Test Link:
- https://www.northerntrailoutfitters.com/default/homepage?evergageTestMessages=gFUul

### Things to check for:
* **Template-specific documentation**: Is there sufficient information for a Template Developer to use the Global Template and customize it for their own use?
* **Campaign stats tracking:** Do impression stats and click stats fire for both the Control and Test experience?

### Additional Notes and Concerns:
- TODO

#### TODOs
- Handlebars comment 
- JS doc comments

2020-09-25 20:22 UTC, amaskiellEG commented on redirect/client.js
> +        }, (Evergage.getConfig().hideContentSectionsMillis || 2500));
This might not be necessary, but I thought it wouldn't hurt to have a fallback for removing the `style` tag added by this Template.

The other is to prevent someone from indefinitely seeing a white screen in the Template Editor. Admittedly, the experience right now is a little odd, so maybe it'd be better to just call `removeTemplateCss(context)` if `(window.frameElement || {}).id !== "sideEditorFrame"`?

2020-10-21 15:02 UTC, avkieu requested changes

2020-10-21 15:02 UTC, avkieu commented on redirect/template.ts
> +    private prepareUrlForRedirect(): string {
Let's not do this, we aren't in the business of telling clients they have to use https. If I put in http, i expect http.

2020-10-23 06:43 UTC, nriserEG requested changes

2020-10-27 19:44 UTC, amaskiellEG commented on redirect/client.js
> +        } else if (context.targetPage.includes(window.location.hostname + window.location.pathname)) {
In revisiting this, yeah, I totally agree. Did you have something like this in mind?
```
function apply(context, template) {
    if ((window.frameElement || {}).id === "siteEditorFrame") {
        removeTemplateCss(context);
        return;
    }

    if (context.targetPage.includes(window.location.hostname + window.location.pathname)) {
        ...
```

2020-10-27 19:46 UTC, avkieu commented on redirect/client.js
> +        } else if (context.targetPage.includes(window.location.hostname + window.location.pathname)) {
```
function apply(context, template) {
    if ((window.frameElement || {}).id === "siteEditorFrame") {
        removeTemplateCss(context);
        return;
    }

    if (!context.targetPage.includes(window.location.hostname + window.location.pathname)) {
        return;
    }
    ...
```

2020-10-28 15:24 UTC, amaskiellEG commented on redirect/client.js
> +        if ((window.frameElement || {}).id === "siteEditorFrame") {
Yeah, that's a good idea, though it's necessary to _prevent_ testing in the template editor (i.e. prevent the entire page you're on from being hidden when you open the template)

2020-10-28 15:26 UTC, amaskiellEG commented on redirect/template.ts
> +    @subtitle("Requires full URL string, including https://, and operates on exact match criteria")
Isn't that grammatically incorrect?

2020-10-28 15:26 UTC, amaskiellEG commented on redirect/template.ts
> +    @subtitle("New destination. Requires full URL string, including https://")
https://github.com/evergage/evergage-global-templates/pull/20#discussion_r513537199

2020-10-28 15:41 UTC, amaskiellEG commented on redirect/client.js
> +    function removeTemplateCss(context) {
I think this was here because I had started working on the template with the old flicker defender code (which was reshowing the "body" too early). It very well might be unnecessary since I don't think the template is sending an `onTemplateDisplayEnd` event.

The other reason I had it was to remove the CSS tag hiding the body when the Template Editor and/or Campaign Editor was open. However, this might also not be necessary if we remove the CSS in the template entirely, since the new Flicker Defender changes also prevent Flicker Defender from running when in either of the editors.

Thoughts on that?

2020-10-28 16:13 UTC, nriserEG commented on redirect/template.ts
> +    @subtitle("Requires full URL string, including https://, and operates on exact match criteria")
This is another case where it's better to stay consistent with other templates.
Also, these subtitles are already grammatically incorrect (no subject, etc), since they're written as shorthands to keep them concise

2020-10-29 13:56 UTC, amaskiellEG commented on redirect/client.js
> +        if ((window.frameElement || {}).id === "siteEditorFrame") {
@nriserEG - With my latest commit, this line changed a little bit; could you take a look and see if the comment I added looks good to you?

2020-10-29 14:14 UTC, amaskiellEG commented
@avkieu, @nriserEG - So in looking into why I had `removeTemplateCss` (https://github.com/evergage/evergage-global-templates/pull/20#discussion_r513549569), I realized from looking into something else for the Flicker Defender changes that we could use an unresolved `Promise` in `apply` to prevent the redirect content zone from being reshown before redirecting.

To illustrate why the CSS was necessary _without the `Promise`_, I've created a simple test here:
https://cumulusfinserv-dev.herokuapp.com/company/about-us

Depending on how quickly the page changes, you may very well briefly see the "About Us" page before being redirected to the Contact Us page. If you look at the logging in the JS console (which is some admittedly excessive logging I've been using for testing the Flicker Defender updates), you'll see that there's an `OnTemplateDisplayEnd` event (the start of which is indicated by the `------------OnTemplateDisplayEnd------------` log) being dispatched, and which Flicker Defender uses to determine whether a content zone that's been hidden should be reshown.


Contrary to that, the redirect on this page uses the changes in my latest commit, which remove the need for template CSS and use an unresolved `Promise` in `apply`:
https://cumulusfinserv-dev.herokuapp.com/insurance/

Unlike on "About Us", you'll notice that there's no logging for the `OnTemplateDisplayEnd` event, meaning that the unresolved `Promise` is preventing one from being dispatched and therefore preventing the redirect content zone from being shown while we're redirecting. We also don't have to worry about that content zone indefinitely being hidden, since the redisplay timeout in Flicker Defender will reshow the page if it takes longer than the value of the redisplay timeout.


Sorry for the somewhat big change, but I'm hoping that will make this template just as effective but _much_ simpler 🙂  Let me know if you have any questions/concerns!

2020-10-29 16:32 UTC, amaskiellEG commented
I think the maintain query params handling needs to be refined, as well; at the moment, we wouldn't capture any of the query params from something like this:

https://developer.evergage.com/getting-started#data-modeling?evergageTestMessages=true

I'm thinking that it'd maybe be safer to use RegEx to strip those from the `href`?

2020-11-04 18:35 UTC, avkieu commented on redirect/README.md
> +TODO (gif?)
just don't put anything

2020-11-04 18:37 UTC, avkieu commented on redirect/client.js
> +    function removeTemplateCss(context) {
I think it might make sense to use JS to hide the body again at the beginning of apply (if not in the VE), even if flicker defender is still active. Just in case the flicker timeout happens while the page is navigating.

2020-11-04 18:52 UTC, amaskiellEG commented on redirect/README.md
> +TODO (gif?)
Sorry, forgot to remove that! Nikki and I talked about not putting anything on Monday 🙂

2020-11-04 19:07 UTC, nriserEG commented on redirect/evergage-gear.json
> +{
wrong file name
Must be evergage-template.json or this template won't work

2020-11-04 19:17 UTC, amaskiellEG commented on redirect/client.js
> +    function removeTemplateCss(context) {
I guess my thought was that if people have a problem with that, they could just up the timeout value for Flicker Defender.

We could definitely do what you're suggesting, but I worry about needing to make changes to the Template itself instead of changing a setting in the platform if there was an issue with pages reshowing.

If we hide again in apply, I think it might make more sense to do that just before calling `sendStat` and assigning the `href`. What do you think?

2020-11-04 19:17 UTC, amaskiellEG commented on redirect/evergage-gear.json
> +{
I can't believe I did that... thank you for catching that 😅

2020-11-04 19:25 UTC, avkieu commented on redirect/client.js
> +    function removeTemplateCss(context) {
Yeah, that's a fine spot to put it.

I do think it makes sense to do in the template, and no require changing the timeout for Flicker Defender because:

The flicker defender timeout should be relative to the timing for 1) getting a response back + 2) the page loading.

In this scenario, we actually want the content hidden for the duration of 1) getting the reponse back + 2) the clients server responding to the request for the next page.

The 2 in the latter scenario could take longer than the 2 in the first scenario, and it'd be overkill to make flicker timeout always long enough to handle the redirect case if it is indeed longer.

2020-11-04 21:18 UTC, avkieu submitted a review, later dismissed
Security Approved

2020-11-05 04:59 UTC, nriserEG commented on redirect/README.md
> +This global template redirects the target webpage to another wepage, based on the URLs provided for each.
```suggestion
This global template redirects the target webpage to another webpage, based on the URLs provided for each.
```

2020-11-05 05:18 UTC, nriserEG commented on redirect/client.js
> +         */
```suggestion
        /** Prevent redirect from occurring while in either the Template Editor or Campaign Editor. */
```

2020-11-05 09:37 UTC, nriserEG commented on redirect/client.js
> +                window.location.href = context.urlForRedirect + ((context.maintainQueryParams && window.location.href.match(/\?.*/gim)[0]) || "");
Rework the logic here. Redirect fails due to code error-ing out here ("Cannot read property '0' of null").
<img width="1792" alt="Screen Shot 2020-11-05 at 12 37 44 AM" src="https://user-images.githubusercontent.com/32201252/98220799-b5c6ce00-1f03-11eb-8ed7-46cfbbbff974.png">

Use a ternary statement that checks for `maintainQueryParams`, and have it output the redirect link with query params if true and empty string if false.

2020-11-05 18:08 UTC, amaskiellEG commented on redirect/client.js
> +                window.location.href = context.urlForRedirect + ((context.maintainQueryParams && window.location.href.match(/\?.*/gim)[0]) || "");
Hmmm, I thought I had added another check for that, but I guess not! Thanks for catching this 🙂

2020-11-05 18:47 UTC, amaskiellEG commented on redirect/client.js
> +         */
So I specifically called out that part of the conditional, since the other part of it prevents redirecting if the Template isn't on the correct page.

For instance, this URL https://cumulusfinserv-dev.herokuapp.com/banking/?evergageTestMessages=t182n is forcing the "Locations to News" Campaign, but no redirect occurs because the target page is different than the page currently being visited.

I didn't think it really made sense to break them out into two different `if` statements, since we're going to return early in both cases.

With all that in mind, do you think my comment is ok?

2020-11-06 04:49 UTC, nriserEG commented on redirect/template.hbs
> +    This global template redirects the target webpage to another wepage, based on the URLs provided for each.
Add a note here (or maybe under a separate "Notes" section) that the template is set up to not redirect while in the editor.

2020-11-06 05:10 UTC, nriserEG commented on redirect/client.js
> +                && window.location.href !== context.urlForRedirect) {
The way it's written right now, the template will redirect from _any_ non-targetPage page. So for example, if targetPage is the _About Us_ page and urlForRedirect is the _Locations_ page on cumulus, navigating from a non-targetPage like homepage actually redirects to the _Locations_ page. We could ensure that we redirect only from targetPage by this: 
```suggestion
            if ((context.targetPage && context.urlForRedirect)
                && window.location.href === context.targetPage) {
```

2020-11-06 05:11 UTC, nriserEG commented on redirect/template.ts
> +    targetPage: string;
Let's rename this to `targetPageURL`

2020-11-06 05:12 UTC, nriserEG commented on redirect/template.ts
> +    urlForRedirect: string;
Let's rename this to redirectURL

2020-11-06 05:27 UTC, nriserEG commented on redirect/client.js
> +            || !context.targetPage.includes(window.location.hostname + window.location.pathname.replace(/\/$/gim, ""))) {
Simplify the regex. No need for the extra modifiers. 
```suggestion
            || !context.targetPage.includes(window.location.hostname + window.location.pathname.replace(/\/$/, ""))) {
```

2020-11-06 06:11 UTC, nriserEG commented on redirect/client.js
> +                    ? window.location.href.match(/\?.*/gim)[0]
You can simply use window.location.search to grab all query parameters. 
```suggestion
                    ? window.location.search
```

2020-11-06 06:13 UTC, nriserEG commented on redirect/client.js
> +                context.paramsForRedirect = (context.maintainQueryParams && window.location.href.match(/\?.*/gim))
`context.maintainQueryParams && window.location.href.match(/\?.*/gim)` outputs an array:
<img width="1567" alt="Screen Shot 2020-11-05 at 10 08 52 PM" src="https://user-images.githubusercontent.com/32201252/98332430-8079b900-1fb3-11eb-9c82-4bbfd3409bac.png">

Even though it could still evaluate to true, this should be rewritten so that the second condition properly returns a boolean

2020-11-06 07:32 UTC, nriserEG commented
@amaskiellEG 
When testing this template, I haven't had successful redirects from pages other than the homepage. Realized it's because the template doesn't even get returned on these pages. Let's investigate this further on Monday.

2020-11-09 18:58 UTC, amaskiellEG commented on redirect/client.js
> +                && window.location.href !== context.urlForRedirect) {
I'm not sure that's the case, since it shouldn't even reach this conditional if we're not on the target page, due to `!context.targetPage.includes(window.location.hostname + window.location.pathname.replace(/\/$/gim, ""))`

2020-11-09 18:59 UTC, amaskiellEG commented on redirect/client.js
> +                    ? window.location.href.match(/\?.*/gim)[0]
This doesn't always work, such as the following scenario: https://github.com/evergage/evergage-global-templates/pull/20#issuecomment-718872467

2020-11-09 19:06 UTC, amaskiellEG commented on redirect/client.js
> +                context.paramsForRedirect = (context.maintainQueryParams && window.location.href.match(/\?.*/gim))
My thinking was that we don't even want to bother with a call to `match` if the params aren't being included, and I think evaluating `context.maintainQueryParams` first would prevent that, right? (I could very well be mistaken but that was my line of thinking anyway.)

Regardless, `match` with either return an array (truthy) or `null` (falsey) which should result of the ternary being evaluated correctly. If you're saying that you think this should _strictly_ result in a boolean, I could change it to `(context.maintainQueryParams && Array.isArray(window.location.href.match(/\?.*/)))`

2020-11-09 19:21 UTC, nriserEG commented on redirect/client.js
> +                && window.location.href !== context.urlForRedirect) {
See example:
<img width="1792" alt="Screen Shot 2020-11-09 at 11 21 10 AM" src="https://user-images.githubusercontent.com/32201252/98586532-ad60f100-227d-11eb-8019-eb616c2aed52.png">

Campaign runs on homepage, even with targetPage not set to it

2020-11-09 22:13 UTC, nriserEG commented on redirect/client.js
> +            || !(currentPage.includes(targetPage) && targetPage.includes(currentPage))) {
So this won't work for cases like:
```js
target page = https://cumulusfinserv-dev.herokuapp.com
current page = https://cumulusfinserv-dev.herokuapp.com?queryparam
target page = https://cumulusfinserv-dev.herokuapp.com?queryparam
current page = https://cumulusfinserv-dev.herokuapp.com
```
because `!(A.includes(B) && B.includes(A))` will always evaluate to `!(A === B)`, and then `A !== B`. 

What you could do is something like, make an array of all the different components of the URL for both current page and target page, and check to see if the current page array contains every element in the target page array. I believe URLSearchParams() https://www.sitepoint.com/get-url-parameters-with-javascript/ may be useful to do something similar

2020-11-10 15:53 UTC, avkieu commented on redirect/client.js
> +            || !(currentPage.includes(targetPage) && targetPage.includes(currentPage))) {
I'm fine with us actually not allowing the case you presented. We could call it out in the doc and template devs are welcome to change the logic, but it's a kinda risky redirect to support that (in regards to infinite loops due to a server-side redirect adding query params, which isn't uncommon).

2020-11-10 16:19 UTC, amaskiellEG commented on redirect/client.js
> +            || !(currentPage.includes(targetPage) && targetPage.includes(currentPage))) {
@avkieu I have some changes that address some of Nikki’s concerns above, but I haven’t pushed them up yet, so as not to cause any confusion.

To what degree should we care about query params that might be present in the URL entered in the target field? What do you think the desired behavior should be?

2020-11-10 19:01 UTC, nriserEG commented on redirect/client.js
> +            || !(currentPage.includes(targetPage) && targetPage.includes(currentPage))) {
@amaskiellEG Let's go with the simplest solution for now and not worry about query params cases as Alex suggested. So the approach should just be `window.location.href !== context.targetPage`, where the URLs are stripped of query params for the comparison.

2020-11-10 19:30 UTC, amaskiellEG commented on redirect/client.js
> +            || !(currentPage.includes(targetPage) && targetPage.includes(currentPage))) {
@nriserEG - Should we be stripping query params from _both_ of the URLs provided by the user? 

@avkieu - When you say "call it out in the doc", do you mean in the Handlebars comment or is there another doc you have in mind?

2020-11-10 19:30 UTC, amaskiellEG commented on redirect/client.js
> +                && window.location.href !== context.urlForRedirect) {
@nriserEG - This should be fixed with my latest commit.

2020-11-10 19:43 UTC, nriserEG commented on redirect/client.js
> +            || !(currentPage.includes(targetPage) && targetPage.includes(currentPage))) {
@amaskiellEG Yes on stripping from both URLs, and regarding the "call it out in the doc", let's add the comment/note in Handlebars for now, under "Customizations".

2020-11-10 21:05 UTC, amaskiellEG commented on redirect/client.js
> +            || !(currentPage.includes(targetPage) && targetPage.includes(currentPage))) {
@nriserEG I added it to "Notes" for now, since it looked a little silly to have 3 different sections, each of which with only 1 item 😬  Let me know if you think it should be different.

2020-11-12 21:08 UTC, nriserEG requested changes

2020-11-12 21:08 UTC, nriserEG commented on redirect/client.js
> +        if ((window.frameElement || {}).id === "siteEditorFrame" || currentPage !== targetPage) {
Add a check for `redirectUrl` here
```suggestion
        if ((window.frameElement || {}).id === "siteEditorFrame" || currentPage !== targetPage || !context.redirectUrl) {
```

2020-11-12 21:08 UTC, nriserEG commented on redirect/client.js
> +        });
The `window.location.href !== context.redirectUrl` check is unnecessary since you're already doing a check for `currentPage !== targetPage` in the previous `if` statement on line 11. `context.redirectUrl` should just be checked in the `if` statement on line 11 as well. 

Remove this `if` statement (lines 16-17, 36) wrapper entirely, and add a check for `redirectUrl` in the `if` statement on line 11 instead. See my other comment. 

```suggestion
        return new Promise((resolve, reject) => {
            Evergage.cashDom("body").css("visibility", "hidden");

            Evergage.sendStat({
                campaignStats: [
                    {
                        control: false,
                        experienceId: context.experience,
                        stat: "Impression"
                    }
                ]
            });

            context.paramsForRedirect = (context.maintainQueryParams && window.location.href.match(/\?.*/))
                ? window.location.href.match(/\?.*/)[0]
                : "";

            window.location.href = context.redirectUrl + context.paramsForRedirect;
        });
```

2020-11-12 21:33 UTC, amaskiellEG commented on redirect/client.js
> +        if ((window.frameElement || {}).id === "siteEditorFrame" || currentPage !== targetPage) {
This would only check that the field isn't empty, but it wouldn't account for the scenario where `window.location.href` is equal to the redirect URL, which needs to be checked so that we don't risk landing in a loop of redirecting to the page we're currently on.

2020-11-12 21:53 UTC, amaskiellEG commented on redirect/client.js
> +        });
The check against the redirect URL is still necessary, but yes, it can now be included in the `if` statement. I'm thinking that it should be making the comparison for the `redirectUrl` similarly to the way it's being done for the `targetPageUrl`.

2020-11-12 22:47 UTC, nriserEG commented on redirect/client.js
> +        if ((window.frameElement || {}).id === "siteEditorFrame" || currentPage !== targetPage) {
@amaskiellEG Doesn't the `currentPage !== targetPage` already account for that? The Promise will run if and only if currentPage === targetPage. So in other words, the Promise won't run if currentPage is equal to the redirect URL.

2020-11-12 23:00 UTC, amaskiellEG commented on redirect/client.js
> +        if ((window.frameElement || {}).id === "siteEditorFrame" || currentPage !== targetPage) {
The target page and redirect URL are 2 different things.

Target page is page that's landed on, while the redirect URL is the page to which we're sending someone. While I'd like to think that someone would be smart enough to make sure that this Template wouldn't load on a page to which it's also supposed to redirect, I'd rather not even allow for the possibility of trying to do the redirect if we land on a page that matches the redirect URL (i.e. if the redirect URL is https://www.northerntrailoutfitters.com/default/homepage and we land on that URL, we shouldn't try to redirect to it).

2020-11-12 23:35 UTC, nriserEG commented on redirect/client.js
> +        if ((window.frameElement || {}).id === "siteEditorFrame" || currentPage !== targetPage) {
If the Promise can only run on pages where `currentPage === targetPage` is true, that means it can't run on the redirectURL. Unless target URL happens to equal redirect URL -- is that the condition you're trying to avoid? If so, then what you're trying to do makes sense.

2020-11-13 16:22 UTC, amaskiellEG commented on redirect/client.js
> +        if ((window.frameElement || {}).id === "siteEditorFrame" || currentPage !== targetPage) {
Yeah, that's at least one condition I had in mind. Considering the potential negative impact of an infinite redirect loop, I think it's worth explicitly protecting against it.

2020-11-13 17:15 UTC, nriserEG requested changes
Updates look good! A lot cleaner now 👍 I added minor review comments for final touches.

Let's also include this in CSS to stay consistent with other global templates without CSS:
`/* Left intentionally blank. CSS is not needed for this template. */`

Otherwise good to go!

2020-11-13 17:15 UTC, nriserEG commented on redirect/client.js
> +        if ((context.targetPageUrl && context.redirectUrl) && (currentPage !== targetPage && currentPage === redirectPage)) {
Looks good! Line's getting a bit long. Let's split this into two lines.
```suggestion
        if ((context.targetPageUrl && context.redirectUrl) && 
            (currentPage !== targetPage && currentPage === redirectPage)) {
```

2020-11-13 18:22 UTC, amaskiellEG commented on redirect/client.js
> +        }
I agree :) It felt right to separate out too after moving that other logic like you had suggested, so thanks!

2020-11-13 20:18 UTC, nriserEG approved these changes
Approved! Another template down! 😺 👍

2020-11-19 16:43 UTC, avkieu approved these changes
Security Approved

2020-12-02 04:51 UTC, merged