EVG-12558/EVG-12559/EVG-12560/EVG-12561/EVG-12562/EVG-12602 - Global Template Updates
evergage/evergage-global-templates pull request #21
Opened 2020-10-06 09:20 UTC by nriserEG

## Template Updates: Exit Intent Pop-up with Exit Intent

Made global template updates, including:
- Updates to Serverside defaults and config names/descriptions
- Delete README.md that contained all templates, and instead add a templates-specific README.md to each individual template folder.
- Change template folder names to match new template names
- HTML, CSS, JS, and TS refactors and updates
- Updates to Handlebars and other code comments
- Update reset function to reset specific template using campaign id and experience id (via `data-evg-campaign-id` and `data-evg-experience-id` attribute selectors)
- DisplayUtils bind/unbind with unique ID (for both Exit Intent Popup and Exit Intent Popup with Email Capture templates)

Please review the individual commits (with JIRA ticket numbers written) to review the updates for each respective template.
 
## JIRA

- Banner with Call-To-Action: https://help.evergage.com/browse/EVG-12602
- Einstein Content Recs: https://help.evergage.com/browse/EVG-12558
- Einstein Product Recs: https://help.evergage.com/browse/EVG-12559
- Exit Intent Pop-Up With Email Capture: https://help.evergage.com/browse/EVG-12561
- Exit Intent Pop-Up: https://help.evergage.com/browse/EVG-12560
- Google Analytics Segment Push: https://help.evergage.com/browse/EVG-12562

## Testing

- Banner with Call-To-Action
    - eng1:globaltemplates
    - Template: [EVG-12602] Banner with Call-To-Action
    - Campaign: [EVG-12602] Banner with Call-To-Action
    - Test Campaign Link: https://www.northerntrailoutfitters.com/default/homepage?evergageTestMessages=zHv3b
- Einstein Content Recs
    - eng1:globaltemplates_cumulus
    - Template: [EVG-12558] Einstein Content Recommendations
    - Campaign: [EVG-12558] Einstein Content Recommendations
    - Test Campaign Link: https://cumulusfinserv.com/?evergageTestMessages=O9aoi
- Einstein Product Recs
    - eng1:globaltemplates
    - Template: [EVG-12559] Einstein Product Recommendations
    - Campaign: [EVG-12559] Einstein Product Recommendations
    - Test Campaign Link: https://www.northerntrailoutfitters.com/default/homepage?evergageTestMessages=8otUB
- Exit Intent Pop-Up With Email Capture
    - eng1:globaltemplates
    - Template: [EVG-12561] Exit Intent Popup with Email Capture
    - Campaign: [EVG-12561] Exit Intent Popup with Email Capture
    - Test Campaign Link: https://www.northerntrailoutfitters.com/default/homepage?evergageTestMessages=iqXWd
- Exit Intent Pop-Up: 
    - eng1:globaltemplates_cumulus
    - Template: [EVG-12560] Exit Intent Pop-up
    - Campaign: [EVG-12560] Exit Intent Pop-up
    - Test Campaign Link: https://cumulusfinserv.com/?evergageTestMessages=niwQr
- Google Analytics Segment Push: 
    - eng1:globaltemplates
    - Template: [EVG-12562] Google Analytics Segment Push
    - Campaign: [EVG-12562] Google Analytics Segment Push
    - Test Campaign Link: https://www.northerntrailoutfitters.com/default/homepage?evergageTestMessages=Wpi0S

Note: 
- For templates on northerntrailoutfitters.com, test with eng1:globaltemplates and force the SDK using this URL: https://eng1.devergage.com/beacon/eng1/globaltemplates/scripts/evergage.min.js
- For templates on cumulusfinserve.com, test with eng1:globaltemplates_cumulus and force the SDK using this URL: https://eng1.devergage.com/beacon/eng1/globaltemplates_cumulus/scripts/evergage.min.js

#### Things to check for:

* **Visuals:** Does it look good across different client sites? To test this, you can use this snippet https://gist.github.com/nriserEG/ff3e0ab870a7dd58b39631c89e367e38 in the Chrome inspector tool that injects the minified template HTML and CSS code (the template will appear at the very top of the page you test on).
* **Deferred rendering:** Is the rendering of the template deferred until the content zone element is loaded on page? 
* **Flicker defense:** Is the template flicker-defensed? Promise must be returned in the apply function for flicker defense to work. 
* **Campaign stats tracking:** Do impression stats and click stats (upon clicking the CTA) fire for both the control and test experience?
* **Template-specific documentation**: Is there sufficient information for a template developer to use the global template and customize for their own use?
* **WCAG compliant:** Does the template contain ARIA attributes and use semantic elements for web accessibility? 
** FYI for this template specifically, I included aria-label attributes and adds fallback background colors in case the background image fails to load.
** You can use the WAVE Chrome extension tool https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh for a quick check. 
* **Mobile/smaller screen responsiveness:** Does the campaign generally look good on smaller screens?

**Important note:** In order to test Flicker Defense properly, we want to test the template on a site that already loads Beacon v16 for the account and dataset being used in testing. Since NTO currently has a Beacon with a different account and dataset than what is being used for testing, you will always see a little flicker while the Beacon is being replaced.

2020-10-07 15:22 UTC, avkieu submitted a review, later dismissed
Security Approved

2020-10-12 22:26 UTC, dcohenEG requested changes

2020-10-14 00:59 UTC, nriserEG commented on einstein-content-recommendations/template.hbs
>      6) Change the value of the aria-label attribute as necessary.
Actually, I left this singular since I use only one aria-label attribute in this template.

2020-10-14 01:00 UTC, nriserEG commented on banner-with-cta/template.hbs
>      Evergage.DisplayUtil.pageElementLoaded in Clientside Code that waits for the content zone to load into the DOM.
Great catch, thank you!

2020-10-14 01:03 UTC, nriserEG commented on banner-with-cta/template.hbs
> +    <h1 class="evg-header evg-h1 evg-display-2 {{style.className}}{{#unless headerVisibility}} evg-hide{{/unless}}">
@dcohenEG Yeah, we have a bug fix request ticket here: https://help.evergage.com/browse/EVG-12785

2020-10-14 04:04 UTC, nriserEG commented on exit-intent-popup-with-email-capture/client.js
> +        Evergage.DisplayUtils.bind(getBindId(context)).pageExit(500).then(() => {
thanks for the catch!

2020-10-14 05:35 UTC, nriserEG commented on exit-intent-popup-with-email-capture/template.hbs
> +        <button class="evg-btn-dismissal evg-style-text {{style.className}}" data-evg-dismissal
@dcohenEG Good point! I don't think we've established official stances. I'll check with Max on this, but here are my initial thoughts:

**Should this send a "dismissal" stat even after you have filled out your email and see the confirmation?**

--> No, it probably shouldn't. If we decide not to, I could add this line of JS in Clientside that removes the "data-evg-dismissal" attribute from the "X" button when the second panel is shown:
```
Evergage.cashDom("#evg-exit-intent-popup-email-capture .evg-btn-dismissal").removeAttr("data-evg-dismissal") 
```

**Should it be a dismissal if you click out of the popup (which effectively dismisses it)?**

--> Possibly, but similar to the issue you brought up in your first question, dismissal tracking via the overlay while on the first panel would make sense but it may not make sense while on the confirmation panel, after you have already filled out your email. 

Side note: I just realized that we don't have a "data-evg-dismissal" attribute on the out-out message so I'll add that to my next commit to make sure we track that.

Let me know your thoughts. I'll check with Max too

2020-10-14 17:47 UTC, nriserEG commented on exit-intent-popup-with-email-capture/template.hbs
> +        <button class="evg-btn-dismissal evg-style-text {{style.className}}" data-evg-dismissal
@dcohenEG I checked with Max. We're going with no dismissal stat (via overlay or "X") once you reach the confirmation panel. I'll make the updates!

2020-10-15 05:14 UTC, nriserEG commented on exit-intent-popup-with-email-capture/template.hbs
> +        <button class="evg-btn-dismissal evg-style-text {{style.className}}" data-evg-dismissal
@avkieu @dcohenEG I looked into how I could accomplish removing dismissal tracking while on the confirmation panel (after successful email submit) and believe the best way is to add a namespace (e.g. "statTrack") to the click event in the [Campaign Stats Tracking Gear](https://github.com/evergage/evergage-product/blob/master/analytics/excavator/src/main/resources/built-in/gears/campaign-stats-tracking/campaignStatsTracking.js) in `bindCampaignClickthroughsAndDismissals` (lines 122-123):

current:
```javascript
const bindCampaignClickthroughsAndDismissals = (campaignElement) => {
    const elements = getCampaignClickthroughAndDismissalElements(campaignElement);
    elements.off("click", sendClickthroughOrDismissal);
    elements.on("click", sendClickthroughOrDismissal);
};
```

change to: 
```javascript
const bindCampaignClickthroughsAndDismissals = (campaignElement) => {
    const elements = getCampaignClickthroughAndDismissalElements(campaignElement);
    elements.off("click.statTrack", sendClickthroughOrDismissal);
    elements.on("click.statTrack", sendClickthroughOrDismissal);
};
```

This way, you can unbind that particular click event from within a template. Example:
```javascript
Evergage.cashDom("#evg-exit-intent-popup-email-capture [data-evg-dismissal]").off("click.statTrack");
```

I updated the Campaign Stats Tracking Gear in eng1:globaltemplates and the **[EVG-12561] Exit Intent Popup with Email Capture** template to test this approach, and it works as expected. Dismissals are trackable while on the first pane but not trackable once you reach the second pane (whether it's via the "X" button or clicking on the overlay outside of the popup). Please feel free to test the template: 

Let me know if you are fine with this approach and I will create a PR for it.

2020-10-15 14:30 UTC, avkieu commented on exit-intent-popup-with-email-capture/template.hbs
> +        <button class="evg-btn-dismissal evg-style-text {{style.className}}" data-evg-dismissal
I'd prefer the template handle this independently. This feels like you're getting clever to "bypass" the stats gear.

By handle it independently I mean, just duplicate the X and overlay without `[data-evg-dismissal]` and show/hide the appropriate version at the appropriate time.

2020-10-15 19:07 UTC, dcohenEG commented on exit-intent-popup-with-email-capture/template.hbs
> +        <button class="evg-btn-dismissal evg-style-text {{style.className}}" data-evg-dismissal
@nriserEG could we possibly get a clone of the template to see what @avkieu suggests here IN THE WILD? I like your approach but I think Alex's is more straightforward since you would only need to look at the Handlebars tab to answer the question "where is a dismissal going to be tracked?"

2020-10-15 20:12 UTC, nriserEG commented on exit-intent-popup-with-email-capture/template.hbs
> +        <button class="evg-btn-dismissal evg-style-text {{style.className}}" data-evg-dismissal
@dcohenEG
I had a separate conversation with @avkieu earlier today about taking yet another approach, which is to update the Campaign Stats Gear, adding a check for `data-evg-clickthrough` and `data-evg-dismissal` attributes in `sendClickthroughOrDismissal` click handler that sends dismissal and clickthrough stats.

I just created a PR for this change: https://github.com/evergage/evergage-product/pull/1552

2020-10-20 01:56 UTC, nriserEG commented
@dcohenEG @avkieu 
I made the following new updates:
- Dan's feedback items, including new dismissal implementation (based on my updates in [EVG-12826](https://help.evergage.com/browse/EVG-12826) / [PR](https://github.com/evergage/evergage-product/pull/1552))
- Minor syntax, naming, and formatting fixes & refactors
- Refactor lighbtox implementation for popups (uses Handlbars #if syntax instead of Clientside implementation)

2020-10-20 14:59 UTC, avkieu approved these changes
Security Approved

2020-10-20 22:35 UTC, nriserEG commented
@dcohenEG @avkieu 
I made the following new updates (Starting with the "Minor fixes" commit):
- Dan's feedback items, including new dismissal implementation (based on my updates in [EVG-12826](https://help.evergage.com/browse/EVG-12826) / [PR](https://github.com/evergage/evergage-product/pull/1552))
- Minor syntax, naming, and formatting fixes & refactors
- Refactor lightbx implementation for popups (uses Handlbars #if syntax instead of Clientside implementation)
- Updates based on discussion with @avkieu in this [separate PR](https://github.com/evergage/evergage-global-templates/pull/22#discussion_r508788313):
-- go back to removing templates via IDs for **non-inline** templates (e.g. `Evergage.cashDom("#evg-template").remove()` ). This applies to the two Recs templates and the Banner template.
-- keep the selector builder approach for **inline** templates (e.g. `Evergage.cashDom("[data-evg-campaign-id=${context.campaign}][data-evg-experience-id=${context.experience}]").remove()` ). This applies to the two Popup templates and the Infobar template, to ensure that we remove/reset the correct single template in cases where a template is used multiple times on a single page.

I updated the test templates in eng1:globaltemplates and eng1:globaltemplates_cumulus

2020-10-21 14:37 UTC, dcohenEG approved these changes
Looks good. Reviewed all the commits since last I reviewed and nothing looks off. Retested the popup campaign with email capture and works as expected.

2020-10-21 14:46 UTC, avkieu approved these changes
Security Approved

2020-10-21 15:54 UTC, nriserEG commented
Thank you @dcohenEG & @avkieu 🙏

2020-10-28 21:54 UTC, merged