EVG-12670 | Infobar with User Attribute and CTA
evergage/evergage-global-templates pull request #22
Opened 2020-10-13 17:40 UTC by amaskiellEG

# Description

Adds the Infobar with User Attribute and CTA Template (using [NTO](https://www.northerntrailoutfitters.com/default/homepage))

This global template places an infobar containing text and a call-to-action button. There are two default Styles: Dark text for lighter backgrounds or light text on darker backgrounds.

## Related Issues/Tickets

JIRA: https://help.evergage.com/browse/EVG-12670

## How to test

#### Template: 
- You can view the demo template in training:amask, **template name: [EVG-12670] Global - Infobar with User Attribute and CTA**. 

#### Campaign: 
- You can view the demo campaign using this template in training:amask, **campaign name: [EVG-12670] Global - Infobar with User Attribute & CTA Test**
_Note: you will need to force the SDK using this URL: https://cdn.evgnet.com/beacon/training/amask/scripts/evergage.min.js_
- Test Links with various layouts: 
-- TODO

### Things to check for:
* **Visuals:** Does it look good across different client sites? To test this, you can copy, paste, and run this snippet in the JS console: TODO (Note that it will appear at the very top of the page.)
* **Mobile/smaller screen responsiveness:** Does the Template generally look good on smaller screens?
* **WCAG compliant:** Does the template contain ARIA attributes and/or use semantic elements for web accessibility? 
** You can use the WAVE Chrome extension tool https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh for a quick check. 
* **Template-specific documentation**: Is there sufficient information for a Template Developer to use the Global Template and customize it for their own use?
------------ ONLY TESTABLE ON NTO -------------
* **Deferred rendering:** Is the rendering of the Template deferred until the Content Zone element is loaded on page? 
* **Flicker defense:** Is the Template flicker-defended?
* **Campaign stats tracking:** Do impression stats and click stats fire for both the Control and Test experience?

**Important note:** In order to test **Flicker Defense** properly, we want to test the template on a site that already loads Beacon v16 for the account and dataset being used in testing. Since [NTO](https://northerntrailoutfitters.com/default/homepage) currently has a Beacon with a different account and dataset than what is being used for testing, you will always see a little flicker while the Beacon is being replaced. Although not as easy to use for testing, another option is to capture the page load with Chrome's performance option and then look at the changes in frame in relation to the Beacon's injection.

2020-10-16 07:34 UTC, nriserEG requested changes

2020-10-16 07:34 UTC, nriserEG commented on infobar-with-user-attribute-and-cta/template.hbs
> +    Customizations:
In Customizations, add note on possibility of referencing other user attributes in Handlebars

2020-10-16 07:34 UTC, nriserEG commented on infobar-with-user-attribute-and-cta/client.js
> +    function buildMsgSelectorFromContext(context) {
```suggestion
    function buildTemplateSelector(context) {
```

2020-10-16 07:34 UTC, nriserEG commented on infobar-with-user-attribute-and-cta/client.js
> +            .remove();
since line 49 is shorter now, let's move .remove() back to line 49

2020-10-16 07:34 UTC, nriserEG commented on infobar-with-user-attribute-and-cta/client.js
> +                .remove();
since line 49 is shorter now, let's move .remove() back to line 49

2020-10-16 07:34 UTC, nriserEG commented on infobar-with-user-attribute-and-cta/template.hbs
> +            {{~/if~}}
Indentation:

```suggestion
            {{~#if preAttrMessageText~}}
                {{~preAttrMessageText~}}
            {{/if~}}
            {{~#if user.attributes.firstName~}}
                {{~user.attributes.firstName~}}
            {{~else~}}
                {{~#if userAttrDefault~}}
                    {{~userAttrDefault~}}
                {{/if~}}
            {{~/if}}
            {{~#if postAttrMessageText~}}
                {{postAttrMessageText}}
            {{~/if~}}
```

2020-10-16 07:34 UTC, nriserEG commented on infobar-with-user-attribute-and-cta/template.hbs
> +                {{~#if userAttrDefault~}}{{~userAttrDefault~}}{{~else}} {{/if~}}
I don't think we need the {{~else}} here. It won't make a difference when you have an empty User Attribute Default field

2020-10-16 20:28 UTC, amaskiellEG commented on infobar-with-user-attribute-and-cta/template.hbs
> +                {{~user.attribute.firstName~}}
Oh good catch!

2020-10-16 20:29 UTC, amaskiellEG commented on infobar-with-user-attribute-and-cta/template.hbs
> +        {{~/if}}
I guess my problem with that is that we'd be rendering unnecessary HTML in the DOM, even in the live Campaign. Doesn't it seem better for us to just conditionally _not_ render anything if it's supposed to be hidden?

2020-10-16 20:31 UTC, amaskiellEG commented on infobar-with-user-attribute-and-cta/template.ts
> +
There's a big convo in there about changing that, though I think Max resolved the convo. He left a note [here](https://docs.google.com/document/d/1ExghP8m8_ku88bCACVZRxqvhQlHN6TRZNiNlsbWSHWA/edit?disco=AAAAHGKDSHk) about it

2020-10-16 20:31 UTC, amaskiellEG commented on infobar-with-user-attribute-and-cta/template.ts
> +
Same as [above](https://github.com/evergage/evergage-global-templates/pull/22#discussion_r506706969)

2020-10-16 20:50 UTC, amaskiellEG commented on infobar-with-user-attribute-and-cta/client.js
> +  })();
Is there some place in particular you have in mind?

2020-10-16 21:05 UTC, amaskiellEG commented on infobar-with-user-attribute-and-cta/template.hbs
> +    Requirements:
I'm realizing that I need to fix the logic in the handlebars HTML a bit, but the idea is that it requires either the user attribute (firstName, in this case) <i>or</i> a default (userAttrDefault).

Either that, or we'd need to do something in clientside JS to send info to the Campaign Debugger tool to let it know that the Template didn't render because the user was missing the given attribute.

2020-10-19 18:06 UTC, amaskiellEG commented on infobar-with-user-attribute-and-cta/template.hbs
> +                {{~#if userAttrDefault~}}{{~userAttrDefault~}}{{~else}} {{/if~}}
Huh, I didn't think that there'd be an empty space there if `userAttrDefault` was left empty but I guess not! Thanks 🙂

2020-10-19 18:18 UTC, amaskiellEG commented on infobar-with-user-attribute-and-cta/template.hbs
> +            {{~/if~}}
I think we can remove the `if` block too!

2020-10-20 00:37 UTC, avkieu requested changes

2020-10-20 00:37 UTC, avkieu commented on infobar-with-user-attribute-and-cta/client.js
> +        Evergage.cashDom("#evg-infobar-with-cta .evg-btn-dismissal").on("click", () => {
This selector doesn't exist in the html (`#evg-infobar-with-user-attr`)

2020-10-20 00:37 UTC, avkieu commented on infobar-with-user-attribute-and-cta/client.js
> +            Evergage.cashDom(buildTemplateSelector(context)).remove();
Remove it by the ID, get rid of this function. Excessive (Keep It Simple)

2020-10-20 00:37 UTC, avkieu commented on infobar-with-user-attribute-and-cta/client.js
> +        Evergage.cashDom(buildTemplateSelector(context)).remove();
Remove it by the ID, get rid of this function. Excessive (Keep It Simple)

2020-10-20 00:37 UTC, avkieu commented on infobar-with-user-attribute-and-cta/template.hbs
> +        {{~/if}}
Uniformity across templates is more valuable than worrying about a little inconsequential html on the page.

2020-10-20 06:36 UTC, nriserEG commented on infobar-with-user-attribute-and-cta/client.js
> +  })();
```suggestion
})();
```

2020-10-20 07:21 UTC, nriserEG commented on infobar-with-user-attribute-and-cta/client.js
> +        });
Remove 53-61, keep it consistent & minimal like the other Infobar template.

2020-10-20 07:57 UTC, nriserEG commented on infobar-with-user-attribute-and-cta/client.js
> +            Evergage.cashDom(buildTemplateSelector(context)).remove();
@avkieu I had originally written the `[data-evg-campaign-id=${context.campaign}][data-evg-experience-id=${context.experience}]` implementation via the Infobar updates I made in this [Template Update PR](https://github.com/evergage/evergage-global-templates/pull/21), from which Andy based off of for this new user attribute Infobar template and made a `buildTemplateSelector` helper function. The reason I changed from simply using the ID to using `[data-evg-campaign-id=${context.campaign}][data-evg-experience-id=${context.experience}]` across templates is so that we can ensure that the correct single template is removed when multiple campaigns running the same template run on the same page, where clients leave the IDs the same across these templates. 

I understand that the reset function in particular runs only when editing the template in the VE, but there could be published templates on page where the clients leave the IDs the same (since they don't bother changing it after cloning global templates). 

Appreciate your thoughts on this.

2020-10-20 14:03 UTC, avkieu commented on infobar-with-user-attribute-and-cta/client.js
> +        Evergage.cashDom(buildTemplateSelector(context)).remove();
apparently we do this in a lot of templates, I suppose we can leave it, but for templates with an `#id` (suggesting there should only ever be one on the page), it is bloat. @nriserEG any thoughts?

2020-10-20 14:08 UTC, amaskiellEG commented on infobar-with-user-attribute-and-cta/client.js
> +  })();
Lol How'd that get there? 🙃

2020-10-20 14:29 UTC, amaskiellEG commented on infobar-with-user-attribute-and-cta/template.hbs
> +        {{~/if}}
I could change the others too, if that's a concern; it doesn't seem like a good practice to be hiding elements that really should be conditionally rendered.

However if that's not something we want to address now, then I can change this to hide with CSS instead.

2020-10-20 14:29 UTC, avkieu commented on infobar-with-user-attribute-and-cta/client.js
> +            Evergage.cashDom(buildTemplateSelector(context)).remove();
We can leave it, but I do think it's excessive for this template. It makes sense in something like a recs campaigns where it would be very intentional to put it on the page twice.

The problem with doing anything "extra" that technically serves no purpose (IMO template's like this should be written to not put itself on the page if it's already on the page) is that the a dev, who may be coming into this template as their first, is going to look at the setup and think to themselves, why did they do X when Y is simpler. And without it being self-evident, they're going to think they are missing something.

2020-10-20 14:47 UTC, avkieu commented on infobar-with-user-attribute-and-cta/template.hbs
> +        {{~/if}}
We're not taking time to change and review **inconsequential** hidden html on the page across multiple templates.

2020-10-20 14:58 UTC, amaskiellEG commented on infobar-with-user-attribute-and-cta/client.js
> +        });
Without this code, control impressions will never be tracked.

Given that this is going to be a global template, and therefore serve as an example, then _not_ including some working control tracking is only going to cause confusion when/if someone uses this template, has a control group, and then sees 0 impressions for that group. Following that scenario, I can only see that leading people to support, eventually.

There's a chance that a developer could figure out how to do this by digging through our docs, but based on experience, this is the kind of thing that most people would write in about.

2020-10-20 15:00 UTC, amaskiellEG commented on infobar-with-user-attribute-and-cta/client.js
> +        Evergage.cashDom("#evg-infobar-with-cta .evg-btn-dismissal").on("click", () => {
It's on line 30: https://github.com/evergage/evergage-global-templates/pull/22/files#diff-c48c157231e98cb78d0644a7a408665b05d0c09d9b1e7cade25c5b5e403f06acR30

2020-10-20 15:02 UTC, amaskiellEG commented on infobar-with-user-attribute-and-cta/client.js
> +        Evergage.cashDom("#evg-infobar-with-cta .evg-btn-dismissal").on("click", () => {
Good catch, thanks!

Side note: this comment was kind of confusing... 😅  Would be clearer to have said something like (it should be `#evg-infobar-with-user-attr`) or (`#evg-infobar-with-user-attr` instead of `#evg-infobar-with-cta`)

2020-10-20 16:04 UTC, amaskiellEG commented on infobar-with-user-attribute-and-cta/template.hbs
> +        {{~/if}}
No problem, I'll change it be consistent with the others.

I think it's worth noting that inconsequential hidden HTML is _not_ the only issue here; it's a bad practice to hide something in templated HTML that could/should be conditionally rendered, and we're basically suggesting that bad practice in the global templates.

It's probably worthwhile to remedy this for the templates we have now sooner than later.

2020-10-20 18:38 UTC, avkieu commented on infobar-with-user-attribute-and-cta/client.js
> +        });
The stats gear tracks a control impression without this. This would actually result in double tracking. Also, we don't expose nor document that control gets passed a context (ala your code have `control()`). It does, but it's not the whole context, because we haven't decided exactly what we want to make available here.

2020-10-20 18:47 UTC, amaskiellEG commented on infobar-with-user-attribute-and-cta/client.js
> +        });
Huh, I didn't realize that we tracked impressions for control by default without adding some kind of HTML attribute (though it makes sense that it works that way, now that I'm looking at the gear again). Apologies for the confusion! 🙈 

Should we just leave control blank then?
```
function control() {

}
```

2020-10-20 19:04 UTC, nriserEG commented on infobar-with-user-attribute-and-cta/client.js
> +            Evergage.cashDom(buildTemplateSelector(context)).remove();
@avkieu Yeah I understand it's a bit extra. I did prefer sticking with removing just with the ID, but went this route because TCs brought up this issue where they had multiple campaigns running the same template on a page. 

However, after giving more thought to this and reminding myself that we want to keep global templates minimal, I agree with you that we should stick with simply removing via IDs. If clients wish to add the same template multiple times on a page, then the developer could customize the template such that it solves for that issue. Perhaps I could add this trick to a possible "Templates Use Cases" doc or something in the near future. Let me know if you have thoughts on this. 

I will change the implementation back to the way it was (removing via IDs) in https://github.com/evergage/evergage-global-templates/pull/21 -- @amaskiellEG could you please fix it back to removing simply via IDs in _this_ PR as well?

2020-10-20 19:35 UTC, nriserEG commented on infobar-with-user-attribute-and-cta/client.js
> +            Evergage.cashDom(buildTemplateSelector(context)).remove();
Updating this thread with a Slack conversation: https://evergage.slack.com/archives/CJDLXS8MT/p1603221004382700

Alex:
> the template id's vs buildTemplateSelector attributes thing. buildTemplateSelector makes sense for inline messages. I wouldn't remove it from those.
> it has a reason for being there for those templates
> All i'm saying is don't do it everywhere because it doesn't serve a purpose everywhere.

@avkieu yes good point. We'll keep it for inline messages (recs templates and the Banner CTA template since these templates could be used on a page multiple times). @amaskiellEG let's remove from this Infobar template 👍  I'll remove it from templates in my separate [PR](https://github.com/evergage/evergage-global-templates/pull/21) where I introduced it.

2020-10-20 20:01 UTC, nriserEG commented on infobar-with-user-attribute-and-cta/client.js
> +        });
@amaskiellEG yes let's leave it blank for consistency. And yea, it makes sense to explicitly add tracking here for control clickthroughs, like we did for recs, where we add evg data attributes so that clicks are tracked via the stats gear.

2020-10-20 21:05 UTC, amaskiellEG commented on infobar-with-user-attribute-and-cta/client.js
> +            Evergage.cashDom(buildTemplateSelector(context)).remove();
@avkieu In looking at this more, I think this might cause issues if there are multiple infobars. Maybe something like this would be better?
```
const templateSelector = buildTemplateSelector(context);
Evergage.cashDom(`${templateSelector} .evg-btn-dismissal`). on("click", () => {
    Evergage.cashDom(templateSelector).remove();
```

2020-10-21 14:09 UTC, avkieu commented on infobar-with-user-attribute-and-cta/client.js
> +            Evergage.cashDom(buildTemplateSelector(context)).remove();
This template should use Ids in all places instead of buildTemplateSelector, in addition to not adding itself to the page if it's already on the page.

Given that, this can just use the ids in both places.



(If this were an inline message that could target multiple content zones on a single page, I would say your solution would be the way to go)

2020-10-21 15:27 UTC, amaskiellEG commented on infobar-with-user-attribute-and-cta/client.js
> +            Evergage.cashDom(buildTemplateSelector(context)).remove();
I did a bit of testing and I think this is the best compromise:
```
function setDismissal() {
    Evergage.cashDom("#evg-infobar-with-user-attr .evg-btn-dismissal").on("click", function() {
        Evergage.cashDom(this).closest("#evg-infobar-with-user-attr").remove();
        Evergage.cashDom("body").css({ "margin-top": "0", "margin-bottom": "0" });
    });
}
```

In the (albeit unlikely) case that 2 infobars using this Template were displayed (for instance, one on top and one on bottom), then using the ID for both would result in _both_ infobars being removed if the first one that's displayed is dismissed. My suggestion above, however, would result in _only_ the correct infobar being removed when dismissed.

2020-10-21 15:33 UTC, amaskiellEG commented on infobar-with-user-attribute-and-cta/client.js
> +            Evergage.cashDom(buildTemplateSelector(context)).remove();
All that being said, this still seems like a better solution to me, since the listener isn't going to get hit twice for whatever template renders first.

```
const templateSelector = buildTemplateSelector(context);
Evergage.cashDom(`${templateSelector} .evg-btn-dismissal`). on("click", () => {
    Evergage.cashDom(templateSelector).remove();
```

2020-10-21 18:14 UTC, avkieu commented on infobar-with-user-attribute-and-cta/client.js
> +            Evergage.cashDom(buildTemplateSelector(context)).remove();
Extract the infobar class logic, make the sector:

``#evg-infobar-with-user-attr.${infobarClass} .evg-btn-dismissal``

2020-10-21 18:55 UTC, amaskiellEG commented on infobar-with-user-attribute-and-cta/client.js
> +            Evergage.cashDom(buildTemplateSelector(context)).remove();
I don't see how this is any better than what I was suggesting, but sure.

2020-10-21 19:22 UTC, avkieu requested changes
The 3 selectors need a dot `.` between the ID and the class.

2020-10-22 17:00 UTC, nriserEG commented on infobar-with-user-attribute-and-cta/template.hbs
> +    https://doc.evergage.com/display/EKB/Modify+Attributes+at+the+User+or+Account+Level
```suggestion
    2) To reference a different user attribute, change the references of 'firstName' to
    the name of the new attribute. More on user attributes here:
    https://doc.evergage.com/display/EKB/Modify+Attributes+at+the+User+or+Account+Level
```

2020-10-22 17:43 UTC, avkieu approved these changes
I'll defer to Nikki on final approval, but I think this will probably be OK after addressing my 2 comments. 

Note: https://help.evergage.com/browse/EVG-12886
We could address the above now for this individual template, though it still needs to be addressed in the other templates.

2020-10-22 17:43 UTC, avkieu commented on infobar-with-user-attribute-and-cta/template.ts
> +            user: context.user
Lets move the logic to get the specific attribute here instead of in clientside.

1. The user object can get rather large.
2. There's lots of values in the user object the a particular implementation may not want to send back down to the client.

2020-10-22 17:43 UTC, avkieu commented on infobar-with-user-attribute-and-cta/client.js
> +        const userAttr = firstName || userAttrDefault;
Along with the suggestion to move this to serverside, the actual value we want is in `firstName.value`.

So this should look more like `const userAttr = (firstName && firstName.value) || userAttrDefault;`

2020-10-22 17:45 UTC, avkieu requested changes
err, put wrong review status

2020-10-22 18:54 UTC, nriserEG commented on infobar-with-user-attribute-and-cta/template.hbs
> +            {{~ctaText~}}
Change HB syntax back to `{{messageText}}` and `{{ctaText}}` for now to be consistent with all of our other templates. Let's address this in a future PR so we can update all templates together.

2020-10-22 19:00 UTC, nriserEG commented on infobar-with-user-attribute-and-cta/client.js
> +        const userAttr = firstName || userAttrDefault;
@amaskiellEG 
In addition to what @avkieu brought up, let's simply line 30 to below so that it's more straightforward:
```
        const firstName = context.user.attributes.firstName.value;
```

2020-10-22 19:11 UTC, avkieu commented on infobar-with-user-attribute-and-cta/client.js
> +        const userAttr = firstName || userAttrDefault;
That would have thrown if firstName is not defined, but you can use optional chaining in TS when you move this server-side (https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining).

2020-10-22 19:11 UTC, amaskiellEG commented on infobar-with-user-attribute-and-cta/template.ts
> +            user: context.user
I had thought about having that logic here, but wasn't sure if that would be preferable. I'll make those changes 🙂

2020-10-22 19:32 UTC, nriserEG commented on infobar-with-user-attribute-and-cta/client.js
> +    }
@amaskiellEG 
Add back this code you took out from here (currently in the apply, lines 33-35), but altered to my suggested code at the bottom of this comment:
```
        context.infobarClass = context.contentZone == "global_infobar_top_of_page"
            ? "evg-infobar-top"
            : "evg-infobar-bottom";
```
- Above code has to do with setting the infobar position so it should be kept in setInfobarPosition()
- I think what you were getting at by removing it is that we don't want to alter context in a function scope. What we could instead do (while keeping this implementation within setInfobarPosition) is to simply create a `infobarClass` variable rather than altering context with `context.infobarClass`.

So: 
```suggestion
    function setInfobarPosition(context) {
        const infobarClass = context.contentZone == "global_infobar_top_of_page"
            ? "evg-infobar-top"
            : "evg-infobar-bottom";
        if (infobarClass === "evg-infobar-top") {
            Evergage.cashDom("body").css({ "margin-bottom": "0", "margin-top": "2.5rem" });
        } else {
            Evergage.cashDom("body").css({ "margin-bottom": "2.5rem", "margin-top": "0" });
        }
    }
```

2020-10-22 19:34 UTC, amaskiellEG commented on infobar-with-user-attribute-and-cta/client.js
> +    }
@nriserEG it was actually done to facilitate this request: https://github.com/evergage/evergage-global-templates/pull/22#discussion_r509542140

2020-10-22 19:37 UTC, nriserEG commented on infobar-with-user-attribute-and-cta/client.js
> +    }
If we're going to make the change here though, then we should make the update in the other infobar template as well for consistency. @avkieu since we don't want to delay the [Template Updates PR](https://github.com/evergage/evergage-global-templates/pull/21) any longer, would you agree that we should postpone making this update in both Infobar templates to a future PR?

2020-10-22 20:06 UTC, nriserEG commented on infobar-with-user-attribute-and-cta/client.js
> +    }
@amaskiellEG Ok I see now, my bad!

2020-10-28 17:47 UTC, avkieu approved these changes
Security Approved

2020-10-29 19:36 UTC, nriserEG commented
@amaskiellEG Don't forget the README!

2020-11-03 03:11 UTC, nriserEG approved these changes

2020-11-04 16:57 UTC, avkieu submitted a review, later dismissed
Security Approved

2020-11-18 16:19 UTC, avkieu approved these changes

2020-11-19 07:57 UTC, nriserEG approved these changes

2020-12-02 04:51 UTC, merged