EVG-12667 | Slide-In with CTA
evergage/evergage-global-templates pull request #23
Opened 2020-10-26 22:35 UTC by amaskiellEG

# Description

Adds the Slide-In with CTA Template (using [NTO](https://www.northerntrailoutfitters.com/default/homepage))

This global template creates a message that slides in from the bottom-right corner of the screen. It contains a header, subheader, and call-to-action button, though each of these is optional.

There are three different triggers for the slide-in: time on page, page sroll, and inactivity on page.

There are two default Styles: dark text for lighter backgrounds or light text on darker backgrounds.

## Related Issues/Tickets

JIRA: https://help.evergage.com/browse/EVG-12667

## How to test

#### Template: 
- You can view the demo template in training:amask, **template name: [EVG-12667] Global - Slide-In with CTA**. 

#### Campaign: 
- You can view the demo campaign using this template in training:amask, **campaign name: [EVG-12667] Slide-In Template Test (no control)**
_Note: you will need to force the SDK using this URL: https://cdn.evgnet.com/beacon/training/amask/scripts/evergage.min.js_
- Test Links with various triggers/layouts: 
-- Page Delay: https://www.northerntrailoutfitters.com/default/homepage
-- Page Scroll: https://www.northerntrailoutfitters.com/default/nutrition
-- Inactivity: https://www.northerntrailoutfitters.com/default/ambassadors

### Things to check for:
* **Visuals:** Does it look good across different client sites? To test this, you can copy, paste, and run this snippet in the JS console: https://gist.github.com/amaskiellEG/21cb127f1f06c88db42c10d0b3d99109 (Note that it will appear at the very top of the page.)
* **Mobile/smaller screen responsiveness:** Does the Template generally look good on smaller screens?
* **WCAG compliant:** Does the template contain ARIA attributes and/or use semantic elements for web accessibility? 
** You can use the WAVE Chrome extension tool https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh for a quick check. 
* **Template-specific documentation**: Is there sufficient information for a Template Developer to use the Global Template and customize it for their own use?
------------ ONLY TESTABLE ON NTO -------------
* **Deferred rendering:** Is the rendering of the Template deferred until the Content Zone element is loaded on page? 
* **Campaign stats tracking:** Do impression stats and click stats fire for both the Control and Test experience?

2020-11-04 18:59 UTC, avkieu requested changes

2020-11-04 18:59 UTC, avkieu commented on slide-in-with-cta/template.ts
> +                this.triggerOptionsNumber = this.secondsOnPage * 1000;
`this.triggerOptionsNumber` doesn't need to exist on the class, nor does it really even need to exist as a local variable here.

you could just `return` instead each case

`return { triggerOptionsNumber: this.secondsOnPage * 1000 }`

2020-11-04 19:58 UTC, avkieu submitted a review, later dismissed
Security Approved

2020-11-19 07:36 UTC, nriserEG requested changes
Added my initial review.

The template renders without any styling applied. Looks like it's just due to using the wrong selector in CSS:
<img width="589" alt="Screen Shot 2020-11-18 at 9 45 23 PM" src="https://user-images.githubusercontent.com/32201252/99622444-65616d00-29e7-11eb-8718-99c9dfbe200d.png">

2020-11-19 07:36 UTC, nriserEG commented on slide-in-with-cta/template.hbs
> +        <p class="evg-header {{style.className}}{{#unless headerVisibility}} evg-hide{{/unless}}" aria-label="{{header}}">
Use h1 instead. Same thing we did for the popup templates https://github.com/evergage/evergage-global-templates/blob/master/exit-intent-popup-with-email-capture/template.hbs

2020-11-19 07:36 UTC, nriserEG commented on slide-in-with-cta/template.hbs
> +        <p class="evg-subheader {{style.className}}{{#unless subheaderVisibility}} evg-hide{{/unless}}" aria-label="{{subheader}}">
Use h2 instead. Same thing we did for the popup templates https://github.com/evergage/evergage-global-templates/blob/master/exit-intent-popup-with-email-capture/template.hbs

2020-11-19 07:36 UTC, nriserEG commented on slide-in-with-cta/evergage-template.json
> +    "name" : "Slide-In With Call-To-Action",
```suggestion
    "name" : "Slide-In with Call-To-Action",
```

2020-11-19 07:36 UTC, nriserEG commented on slide-in-with-cta/client.js
> +                break;
This needs to return a Promise so that the Handlebars Gear won't fire downstream processes prematurely.
```suggestion
                return new Promise((resolve, reject) => {
                    setTimeout(() => {
                        const html = template(context);
                        Evergage.cashDom("body").append(html);
                        setDismissal(context);
                        resolve();
                    }, context.triggerOptionsNumber);
                });
```

2020-11-24 15:14 UTC, amaskiellEG commented on slide-in-with-cta/client.js
> +     * @description Creates unique selector that targets the template.
Just to clarify, you mean across all of the other templates?

2020-11-24 15:15 UTC, amaskiellEG commented on slide-in-with-cta/client.js
> +                break;
Oh right! Great catch, thanks! 🙂

2020-11-24 15:24 UTC, amaskiellEG commented on slide-in-with-cta/template.css
> +}
I think I might've forgotten to test it on mobile....? If it looks fine on mobile using the other keyframe then yeah, definitely makes sense to remove this one 🙂

2020-11-24 15:29 UTC, amaskiellEG commented on slide-in-with-cta/template.hbs
> +    There are three different triggers for the slide-in: time on page, page sroll, and inactivity on page.
I'm ok making these changes though FWIW, I'm not a huge fan of changing "page scroll" to "scroll depth". I have the feeling that was decided because it might make more sense to a business user or something, but I think page scroll is a little bit better since it's just as clear and is consistent with the _actual_ thing being used (`pageScroll`).

2020-11-24 15:35 UTC, amaskiellEG commented on slide-in-with-cta/template.hbs
> +<div class="{{style.className}}" id="evg-slide-in-cta" data-evg-campaign-id="{{campaign}}"
Isn't that counter to what we've been doing for the other Templates?

2020-11-24 15:38 UTC, amaskiellEG commented on slide-in-with-cta/template.hbs
> +        <p class="evg-header {{style.className}}{{#unless headerVisibility}} evg-hide{{/unless}}" aria-label="{{header}}">
I used `p` tags due to Max's mock-up: https://docs.google.com/document/d/1PZh9k_Z-1aDjW0cqP5YXZd0n3BSvey4k9pPJbmYS3wo/edit

I could use h1 and h2, but if I was sticking to his mock-up, I'd basically be making them the same font-size, which seemed.... weird to me? What do you think?

2020-11-24 16:13 UTC, theKevinRobertsExperience commented on slide-in-with-cta/template.hbs
> +    for recommended names for content zones mapped via Sitemap.
`global_slide_in`. Mixing `_` and `-` is confusing.

2020-11-24 16:32 UTC, amaskiellEG commented on slide-in-with-cta/template.hbs
> +        <p class="evg-header {{style.className}}{{#unless headerVisibility}} evg-hide{{/unless}}" aria-label="{{header}}">
What's the reasoning for that? Don't we have aria-labels on the other messages?

2020-11-24 16:59 UTC, amaskiellEG commented
@nriserEG Hmmmm I'm looking at the audits right now and it seems like something weird might've been happening while cloning? At the time when you cloned it, the Handlebars HTML _should've_ had an id of `evg-slide-in-with-cta` but for some reason, your clone had `evg-slide-in-cta`...

Can you try making a clone again like you had previously done and then see if the id is correct in both the HTML and CSS?

2020-11-24 17:09 UTC, nriserEG commented on slide-in-with-cta/template.hbs
> +<div class="{{style.className}}" id="evg-slide-in-cta" data-evg-campaign-id="{{campaign}}"
Actually, it's consistent. Check out the two recs templates and the banner template. 

The idea is that we remove templates via IDs for non-inline templates (e.g. Evergage.cashDom("#evg-template").remove() ). This applies to the two popup templates and the Infobar template, which are expected to each be used only once on a given page. As for inline templates, we implement the selector builder approach (e.g. Evergage.cashDom("[data-evg-campaign-id=${context.campaign}][data-evg-experience-id=${context.experience}]").remove() ) instead of simply using an ID to remove. This applies to the two recs templates and the banner template where a template could be used multiple times on a single page. As for the slide-in, it's technically not an inline template, but I see it as one that could be used multiple times on a page so it makes sense to have a class instead of an ID.

2020-11-24 17:16 UTC, nriserEG commented on slide-in-with-cta/template.hbs
> +        <p class="evg-header {{style.className}}{{#unless headerVisibility}} evg-hide{{/unless}}" aria-label="{{header}}">
No, aria-label is used in cases where a text label is not visible on the screen. We don't do it for elements like pararaph, h*, etc. that contain regular text. It make sense to have it on CTA buttons, input fields, and elements that contain images like rating stars instead of text. Check out our templates

2020-11-24 17:22 UTC, nriserEG commented on slide-in-with-cta/template.hbs
> +    There are three different triggers for the slide-in: time on page, page sroll, and inactivity on page.
Consistency is key here. Stick with scroll depth since that's the official wording we've chosen. Same wording should be used elsewhere. I actually think scroll depth is better -- it's more descriptive than page scroll because it implies that it triggers based on how far you've gone down on a page ("depth").

2020-11-24 17:44 UTC, nriserEG commented
@amaskiellEG I didn't clone any of your templates when I tested. I had uploaded the templates code directly from your feature-EVG-12667-slide-in-with-cta branch. 

So I'm looking at your PR right now, and I still see the HTML referencing #evg-slide-in-cta and CSS referencing #evg-slide-in-with-cta.

Current files from the PR: 
HBS: https://github.com/evergage/evergage-global-templates/blob/edfbf3619b11f958e7ca6dc5a7c158ab233f4a53/slide-in-with-cta/template.hbs
CSS: https://github.com/evergage/evergage-global-templates/blob/edfbf3619b11f958e7ca6dc5a7c158ab233f4a53/slide-in-with-cta/template.css

2020-11-24 18:59 UTC, amaskiellEG commented on slide-in-with-cta/template.hbs
> +<div class="{{style.className}}" id="evg-slide-in-cta" data-evg-campaign-id="{{campaign}}"
Oh, I wasn't aware that we had started doing that...

I'm admittedly a little confused about the reasoning and not entirely sold on the solution, but I think that's a conversation for another time/place 😅 

That being said, I _do_ think it might make sense to use an ID for this, since, with it's current implementation and options, it would functionally act as a pop-up message. I think if we had some kind of option in the config that could be used to control _from where_ the slide-in would appear, then I could see a class being more appropriate.

With that in mind, do you it's ok as is, or should I change the ID to a class?

2020-11-24 19:03 UTC, amaskiellEG commented on slide-in-with-cta/template.hbs
> +        <p class="evg-header {{style.className}}{{#unless headerVisibility}} evg-hide{{/unless}}" aria-label="{{header}}">
Oh huh, I thought we had added them to the other Templates. Thank for clarifying! 🙂

2020-11-24 22:32 UTC, amaskiellEG commented
@nriserEG excluding a few things I haven't gotten confirmation from you about, I've made the changes you suggested.

As part of my work on fixing control impressions for other Templates, it also occurred to me that the same kind of thing would apply to this Template as well. So apologies that the changes in that last commit are a bit big, but that's why they got made a bit late in the review of this 😅

2020-11-25 20:38 UTC, nriserEG commented on slide-in-with-cta/template.hbs
> +        <p class="evg-header {{style.className}}{{#unless headerVisibility}} evg-hide{{/unless}}" aria-label="{{header}}">
Using h1-h6 heading tags matter for accessibility. Keep the current size styling you're using for header and subheader, but switch to using h1 and h2 tags. It's not crucial that we follow the same exact styling that I've outlined in https://developer.evergage.com/templates/template-html-classes-and-css, if that's what you're worried about

2020-11-25 21:18 UTC, nriserEG commented on slide-in-with-cta/template.hbs
> +<div class="{{style.className}}" id="evg-slide-in-cta" data-evg-campaign-id="{{campaign}}"
@amaskiellEG It stemmed out of the conversation in the Infobar with User Attribute template https://github.com/evergage/evergage-global-templates/pull/22#discussion_r508788313 (see also https://github.com/evergage/evergage-global-templates/pull/21#issuecomment-713178796 and https://github.com/evergage/evergage-global-templates/pull/21/commits/f76986814b95473ff502ec515296671a10c999e0) 

So I thought about this more, and you're right, it probably would make sense to use a class only if we have another biz user config that allows users to choose the display location of the template. Good point. With that said, I think we both agree now that this template (as it's currently built) is intended to be used only once on a page (like popup templates like you mentioned). So in that case, to stay consistent with the popup and infobar templates, we should remove the buildTemplateSelector you currently have and simply use the id (so keep the ID you have 👍) to remove the template via reset() and setDismissal(). Like we did here https://github.com/evergage/evergage-global-templates/blob/master/exit-intent-popup/client.js

2020-11-25 21:24 UTC, nriserEG commented on slide-in-with-cta/template.css
> +    }
@amaskiellEG ^^

2020-11-25 21:25 UTC, nriserEG commented on slide-in-with-cta/template.css
> +        font-size: 17px;
@amaskiellEG ^^

2020-11-25 21:55 UTC, nriserEG commented on slide-in-with-cta/client.js
> +     * @description Creates unique selector that targets the template.
Yeah, all other templates as well. If you search "param description" in the repo (linked in my previous comment), you'll see that google analytics segment push, exit intent popup, and infobar templates need to be updated.

2020-11-25 21:59 UTC, nriserEG commented on slide-in-with-cta/template.hbs
> +    1) As a best practice, set the content zone to "global_slide-in". See https://developer.evergage.com/websdk/contentzones
Change to "global_slide_in" as per Kevin's comment

2020-11-25 22:41 UTC, amaskiellEG commented on slide-in-with-cta/template.hbs
> +    1) As a best practice, set the content zone to "global_slide-in". See https://developer.evergage.com/websdk/contentzones
How did I miss that? 🙃

2020-11-25 22:44 UTC, amaskiellEG commented on slide-in-with-cta/template.hbs
> +        <p class="evg-header {{style.className}}{{#unless headerVisibility}} evg-hide{{/unless}}" aria-label="{{header}}">
I guess what I'm more concerned with is that h1 and h2 usually imply relative sizes, in that I'd expect h1 to be bigger than h2, even if only by a small amount. Having those types of tags be the same size just seems... odd? I'd also have to test this, but I wonder if WAVE would throw a warning about them being the same size?

2020-11-25 22:49 UTC, amaskiellEG commented on slide-in-with-cta/template.hbs
> +<div class="{{style.className}}" id="evg-slide-in-cta" data-evg-campaign-id="{{campaign}}"
Ahhh gotcha! Thanks for providing that context 🙂  I'll change it accordingly!

2020-11-25 23:04 UTC, amaskiellEG commented on slide-in-with-cta/client.js
> +     * @description Creates unique selector that targets the template.
Done!

2020-11-25 23:06 UTC, amaskiellEG commented on slide-in-with-cta/template.css
> +    }
Sorry, didn't have a chance to test on mobile yet and wanted to hold off on removing these until I had done that 🙈

2020-11-26 00:18 UTC, nriserEG commented on slide-in-with-cta/template.hbs
> +        <p class="evg-header {{style.className}}{{#unless headerVisibility}} evg-hide{{/unless}}" aria-label="{{header}}">
The reason I said keep the current size styling is that your template already has different sizes for header and subheader. So it's fine
<img width="325" alt="Screen Shot 2020-11-25 at 5 18 39 PM" src="https://user-images.githubusercontent.com/32201252/100293854-44969b80-2f42-11eb-9702-c0fdf51ba62e.png">

2020-11-30 17:37 UTC, amaskiellEG commented on slide-in-with-cta/template.css
> +}
After testing on mobile, I decided having a separate keyframe for it would be good, since the `to` value would be a bit different.

2020-11-30 17:37 UTC, amaskiellEG commented on slide-in-with-cta/template.css
> +    }
Following testing on mobile, removed some of these and kept others 🙂

2020-11-30 17:37 UTC, amaskiellEG commented on slide-in-with-cta/template.css
> +        font-size: 17px;
Done!

2020-11-30 17:38 UTC, amaskiellEG commented on slide-in-with-cta/template.hbs
> +        <p class="evg-header {{style.className}}{{#unless headerVisibility}} evg-hide{{/unless}}" aria-label="{{header}}">
Ohp, you're right! Sorry, I had some weird memory of them being the same at some point 😅  I'll change those elements to h1 and h2

2020-11-30 22:54 UTC, nriserEG commented on slide-in-with-cta/template.hbs
> +        </p>
@amaskiellEG Remember to update the tags to heading tags (h1 and h2). See comments https://github.com/evergage/evergage-global-templates/pull/23#discussion_r526633950 and https://github.com/evergage/evergage-global-templates/pull/23#discussion_r526634536

2020-11-30 23:13 UTC, nriserEG commented on slide-in-with-cta/template.hbs
> +    header, subheader, and call-to-action button.
```suggestion
    This global template creates a message that slides in from the bottom-right corner of the screen,
    and contains a call-to-action button.
```

We want to keep the description here concise -- no need to mention every component of the template. In general, always check for consistency with other templates that are similar / have similar components. In this case specifically, follow the pattern of the exit intent popup templates and the banner templates (all have headers and subheaders).

2020-11-30 23:19 UTC, nriserEG commented on slide-in-with-cta/template.css
> +    padding: 0.5rem 1rem;
Remove the leading zero. See "Don't add leading zeros in property values" mentioned in https://developer.evergage.com/templates/templates-style-guide-and-coding-conventions

2020-11-30 23:19 UTC, nriserEG commented on slide-in-with-cta/template.css
> +        box-shadow 0.15s ease-in-out;
Remove the leading zeros. See "Don't add leading zeros in property values" mentioned in https://developer.evergage.com/templates/templates-style-guide-and-coding-conventions

2020-11-30 23:19 UTC, nriserEG commented on slide-in-with-cta/template.css
> +    transition: background-color 0.15s, color 0.15s;
Remove the leading zero. See "Don't add leading zeros in property values" mentioned in https://developer.evergage.com/templates/templates-style-guide-and-coding-conventions

2020-11-30 23:19 UTC, nriserEG commented on slide-in-with-cta/template.css
> +    padding: 0 0.5rem;
Remove the leading zero. See "Don't add leading zeros in property values" mentioned in https://developer.evergage.com/templates/templates-style-guide-and-coding-conventions

2020-11-30 23:19 UTC, nriserEG commented on slide-in-with-cta/template.css
> +    margin-bottom: 0.5rem;
Remove the leading zero. See "Don't add leading zeros in property values" mentioned in https://developer.evergage.com/templates/templates-style-guide-and-coding-conventions

2020-12-01 03:04 UTC, nriserEG commented on slide-in-with-cta/template.css
> +    font-family: "Helvetica Neue", "Arial", sans-serif;
```suggestion
    font-family: inherit;
```
We don't want to assign font-family. 
See examples in other templates: https://github.com/evergage/evergage-global-templates/search?q=font-family

2020-12-01 03:19 UTC, nriserEG commented on slide-in-with-cta/template.css
> +    z-index: 100000;
I noticed that we haven't been staying consistent with z-index values across templates. Could you please make a separate commit that updates the z-index of the two exit intent popup templates (both use "9999999") and the infobar template (uses "10000000")? Let's use "1000000" for them all.

```suggestion
    z-index: 1000000;
```

2020-12-01 03:30 UTC, nriserEG commented on slide-in-with-cta/template.css
> +    position: relative;
Remove

2020-12-01 03:37 UTC, nriserEG commented on slide-in-with-cta/template.css
> +@keyframes slideInDesktopMessage {
```
@keyframes slideIn {
```

2020-12-01 03:44 UTC, nriserEG commented on slide-in-with-cta/template.css
> +        right: 10%;
```suggestion
        right: 5%;
```

2020-12-01 03:45 UTC, nriserEG commented on slide-in-with-cta/template.css
> +    right: 10%;
```suggestion
    right: 10%;
```

2020-12-01 04:33 UTC, nriserEG commented on slide-in-with-cta/template.css
> +    max-width: 90vw;
Remove max-width

2020-12-01 04:33 UTC, nriserEG commented on slide-in-with-cta/template.css
> +    max-height: 90vh;
Remove max-height

2020-12-01 04:40 UTC, nriserEG commented on slide-in-with-cta/template.css
> +        max-height: 95vh;
Remove max-width and max-height. Unnecessary, as these would make kick in only if the screen size is smaller than 300px, which is an uncommonly small screen size. Also keep in mind that we want to keep global templates styling as minimal as possible

2020-12-01 04:46 UTC, nriserEG commented on slide-in-with-cta/template.css
> +        right: 10%;
```suggestion
        right: 5%;
```

2020-12-01 04:48 UTC, nriserEG commented on slide-in-with-cta/template.css
> +    right: 10%;
```suggestion
    right: 5%;
```

right: 10% positions the template too close to the center. Let's go with 5% instead

2020-12-01 04:58 UTC, nriserEG commented on slide-in-with-cta/template.css
> +    position: absolute;
```suggestion
    position: fixed;
```

2020-12-01 05:37 UTC, nriserEG commented on slide-in-with-cta/template.css
> +}
This can be simplified to this
```suggestion
#evg-slide-in-with-cta .evg-dark-on-light {
    color: #000;
    background-color: #fff;
}
```

2020-12-01 05:50 UTC, nriserEG commented on slide-in-with-cta/template.css
> +}
Simplify to:
```suggestion
#evg-slide-in-with-cta .evg-dark-on-light,
#evg-slide-in-with-cta .evg-cta.evg-light-on-dark {
    color: #000;
    background-color: #fff;
}

#evg-slide-in-with-cta .evg-light-on-dark,
#evg-slide-in-with-cta .evg-cta.evg-dark-on-light {
    color: #fff;
    background-color: #000;
}
```

2020-12-01 06:14 UTC, nriserEG commented
@amaskiellEG Right now, the template is positioned relative to `body`, so it could look like this:
<img width="1792" alt="Screen Shot 2020-11-30 at 7 00 33 PM" src="https://user-images.githubusercontent.com/32201252/100703851-3fc65300-3359-11eb-8a33-fec63dbac4bc.png">

Instead, position the template relative to viewport (`position: fixed`) so that it displays at the bottom right of the page no matter where the user is on the page.

2020-12-01 06:26 UTC, nriserEG commented
@amaskiellEG Template should be good to go after the above fixes 👍

2020-12-01 23:04 UTC, amaskiellEG commented on slide-in-with-cta/template.css
> +    z-index: 100000;
@nriserEG maybe the infobars should be less than the pop-ups and the slide-in? I kinda feel like those should be above an infobar if they happen to overlap, right?

2020-12-01 23:13 UTC, amaskiellEG commented on slide-in-with-cta/template.css
> +    max-width: 90vw;
This is for accessibility concerns.

Believe it or not, we had someone write into support once about a pop-up failing an accessibility test because it "couldn't be dismissed when viewing the pop-up on IE and zoomed-in 200%".  (https://evergage.zendesk.com/agent/tickets/17312)

I know that's kind of a crazy benchmark, but setting the max-width and max-height as I've done here ensures that this won't be an issue with the template.

2020-12-01 23:13 UTC, amaskiellEG commented on slide-in-with-cta/template.css
> +    max-height: 90vh;
see https://github.com/evergage/evergage-global-templates/pull/23#discussion_r533785426

2020-12-01 23:14 UTC, amaskiellEG commented on slide-in-with-cta/template.css
> +        max-height: 95vh;
see https://github.com/evergage/evergage-global-templates/pull/23#discussion_r533785426

2020-12-01 23:23 UTC, amaskiellEG commented on slide-in-with-cta/template.css
> +    position: absolute;
Hm, I thought I changed that? I have it in a local copy of this but I must've not committed it, sorry!

2020-12-02 04:22 UTC, nriserEG commented on slide-in-with-cta/template.css
> +    z-index: 100000;
@amaskiellEG Good call 👍 How about 100000 for infobars, 1000000 for slide-in, and 10000000 for popups (which could have a lightbox overlay that we wouldn't want anything overlapping on top of)? I think it'd look better than doing something like 100001, 100002, 100003

2020-12-02 04:28 UTC, nriserEG commented on slide-in-with-cta/template.css
> +    max-width: 90vw;
I see, that's interesting. Our global templates are written in ES6 though and we implement other things that are not quite compatible with IE so I still think we should remove

2020-12-02 16:07 UTC, amaskiellEG commented on slide-in-with-cta/template.css
> +    z-index: 100000;
Sounds good to me :)

2020-12-02 19:06 UTC, amaskiellEG commented on slide-in-with-cta/template.css
> +    z-index: 100000;
For reference: https://github.com/evergage/evergage-global-templates/pull/23/commits/7affe582eac2607c2b31e26dd082e189b0e29445

2020-12-02 19:10 UTC, amaskiellEG commented on slide-in-with-cta/template.css
> +    max-width: 90vw;
I think it's less an issue with IE, and more "zooming in 200%". I'm not sure _why_ that might be an important test, but the max-widths and max-heights are a pretty low-effort to ensure that the message can always be dismissed. Seems like it's worth it, just to be safe?

2020-12-02 19:38 UTC, nriserEG commented on slide-in-with-cta/template.css
> +    max-width: 90vw;
Ok I'm convinced 👍  I looked it up https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-scale.html and it does say:
> Except for captions and images of text, text can be resized without assistive technology up to 200 percent without loss of content or functionality. (Level AA)

That being said, this is probably something that we should check for all of our templates then. Let's do this in a separate PR (https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008AbDzIAK/view) so we can do a more thorough check across templates.

2020-12-02 19:43 UTC, amaskiellEG commented on slide-in-with-cta/template.css
> +    max-width: 90vw;
Oh, good find! 🙂  Are you ok with me leaving this as is for now and maybe those `max-height` and `max-width` values can be more thoroughly tested whenever the work for that new ticket is done?

2020-12-02 19:59 UTC, nriserEG commented on slide-in-with-cta/template.css
> +    max-width: 90vw;
We should remove from this template for now. Later when we investigate this further, there could be other solutions that we may want to explore. We want to implement things only when they've been thoroughly tested, especially accessibility-related things, and across templates.

2020-12-02 20:08 UTC, amaskiellEG commented on slide-in-with-cta/template.css
> +    max-width: 90vw;
Okie doke! :)

2020-12-02 20:10 UTC, nriserEG commented on slide-in-with-cta/template.css
> +    max-width: 90vw;
Thanks Andy!

2020-12-02 20:13 UTC, amaskiellEG commented on slide-in-with-cta/template.css
> +        max-height: 95vh;
@nriserEG I think we should leave these, though, because I remember that some browser clients on phones _do_ zoom in slightly when rendering pages, which could be problematic if that resulted in the "300px" extending the _actual_ pixel dimension of the screen. It seems like it'd make sense to at least have _some_ kind of safeguard for mobile, since it could easily make the page unusable.

2020-12-02 20:55 UTC, nriserEG commented on slide-in-with-cta/template.css
> +        max-height: 95vh;
@amaskiellEG Adding extra styling should be based on facts/stats and actual use cases so that we don't litter our CSS with unnecessary/outdated styling. We can look into this more in the templates update ticket later, but based on stats of mobile screen resolution https://gs.statcounter.com/screen-resolution-stats/mobile/worldwide, we don't have to worry about phones with resolution lower than 360px resolution/rendered pixels. Keep in mind that we cannot build templates for _all_ phones/screen sizes and instead want to focus on typical sizes.

2020-12-02 22:28 UTC, amaskiellEG commented on slide-in-with-cta/template.css
> +        max-height: 95vh;
My experience with this Campaign that you previously QAed is what I referenced above: https://help.evergage.com/browse/CS-6877

I'm extra wary of the possibility of oversizing and the number of unexpected issues related to that which came up during QA. That being said, I just tested this slide-in on several different devices in Browserstack and they all looked fine, so at least when viewing the page with a normal zoom, it seems those styles may very well not be needed. 

However, I think it's a stretch to say that 2 lines of CSS which would help ensure a possible accessibility concern (and one which we have experienced before in a similar type of message) would be littering the CSS with unnecessary styling; the necessity is preventing an accessibility concern, which has always been one of the primary focuses of our global Templates and is still one of the major sections of [our style guide](https://developer.evergage.com/templates/templates-style-guide-and-coding-conventions).

I tend to consider everything down to 320px, since that's the width of the iPhone 5/SE and seems like, based on stats from that site, it was still the low-end of the range of sizes as of last year: https://gs.statcounter.com/screen-resolution-stats/mobile/worldwide/2019.

2020-12-02 23:12 UTC, nriserEG approved these changes

2020-12-03 15:58 UTC, avkieu approved these changes
Security Approved

2020-12-15 05:11 UTC, merged