Add PR template for GitHub
evergage/evergage-global-templates pull request #26
Opened 2020-11-16 18:18 UTC by amaskiellEG

# Description

Adds a simple PR template, which follows [a naming convention supported by GitHub](https://help.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository). The result is that the texarea field with pre-populate with something like the following whenever someone creates a PR:
![Screen Shot 2020-05-15 at 4 22 04 PM](https://user-images.githubusercontent.com/50626880/82094886-eacc3380-96cb-11ea-8e7f-848c0cb0a7a3.png)

## How to test

- Well, you can't here until this is merged into `master`. However, we have something similar in the [customer repo](https://github.com/evergage/evergage-customer) so you could see how it works by creating a PR there.

#### Similar PRs
https://github.com/evergage/evergage-customer/pull/638
https://github.com/evergage/evergage-developer-docs-static/pull/17

## Note
I've added a few things that seem like they'd be relevant, based on some of other recent PRs in this repo, but please let me know if you think anything should be added/removed/etc.

2020-11-16 18:40 UTC, nriserEG requested changes
Thanks Andy! Requested some minor changes

2020-11-16 18:40 UTC, nriserEG commented on .github/PULL_REQUEST_TEMPLATE.md
> +** You can use the WAVE Chrome extension tool https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh for a quick check.
Let's remove the extra "**"
```suggestion
* **WCAG compliant:** Does the template contain ARIA attributes and/or use semantic elements for web accessibility? You can use the WAVE Chrome extension tool https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh for a quick check.
```

2020-11-16 18:40 UTC, nriserEG commented on .github/PULL_REQUEST_TEMPLATE.md
> +* **Visuals:** Does it look good across different client sites? To test this, you can copy, paste, and run this snippet in the JS console: GITHUB_GIST
I templatized the snippet
```suggestion
* **Visuals:** Does it look good across different client sites? To test this, you can copy, paste, and run this snippet in the JS console: GITHUB_GIST (see template snippet: https://gist.github.com/nriserEG/fcfe7ab7e04d51dbf9cb19fc0476d474)
```

2020-11-16 19:36 UTC, amaskiellEG commented
Thanks for the feedback, @nriserEG! Unless @avkieu or you have anything else to suggest, this should be all set 🙂

2020-11-16 19:44 UTC, nriserEG approved these changes

2020-11-24 17:58 UTC, avkieu approved these changes

2020-12-02 04:50 UTC, merged