@W-8307466@ Update control impression tracking for templates
evergage/evergage-global-templates pull request #27
Opened 2020-11-19 23:16 UTC by amaskiellEG

# Description

This PR ensures that control impressions are tracked for Templates which might be dependent on user behavior in order to be displayed, including:
- Exit-Intent Pop-Up
- Exit-Intent Pop-Up with Email Capture
- Infobar with CTA (maybe?)

## Related Issues/Tickets

GUS: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008AbE9IAK/view

## How to test

_TODO_

2020-11-23 23:14 UTC, amaskiellEG commented
Apologies if I missed anything in the description. Also, I haven't added the the Infobar changes to this PR yet because I wasn't sure if they should be handled in a separate PR for https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008AbDzIAK/view instead.

2020-11-24 17:58 UTC, avkieu requested changes

2020-11-24 17:58 UTC, avkieu commented on exit-intent-popup/client.js
> +        return Evergage.DisplayUtils.bind(buildBindId(context)).pageExit(500).then(() => {
Can we extract the delay ms to a constant (here and in apply)

2020-11-24 17:58 UTC, avkieu commented on exit-intent-popup-with-email-capture/client.js
> +        return Evergage.DisplayUtils.bind(buildBindId(context)).pageExit(500).then(() => {
Can we extract the delay ms to a constant (here and in apply)

2020-11-24 17:58 UTC, avkieu commented on einstein-product-recommendations/client.js
> -        Evergage.cashDom(`${contentZoneSelector} a`).attr("data-evg-clickthrough", "");
Do control clicks track without this. I believe so, but just double checking, because the change you made doesn't set the attribute anymore.

(This comment applies multiple templates)

2020-11-30 18:52 UTC, amaskiellEG commented on einstein-product-recommendations/client.js
> -        Evergage.cashDom(`${contentZoneSelector} a`).attr("data-evg-clickthrough", "");
In all of the Templates, I removed adding the `data-evg-clickthrough` attribute to anchor tags nested under the `contentZoneSelector` element, since it's not necessary. Is that what you're talking about?

2020-12-02 02:20 UTC, nriserEG commented on einstein-product-recommendations/client.js
> -        Evergage.cashDom(`${contentZoneSelector} a`).attr("data-evg-clickthrough", "");
Yeah, control clicks will still be tracked without adding that attribute. Also tested to confirm 👍 I believe that line of code is an artifact from before we made updates to the campaign stats gear. 

Separate issue -- I think we should update the boilerplate template code as well, to keep it all consistent. I made a new GUS ticket here: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008kawxIAA/view. Feel free to add on.

2020-12-02 02:36 UTC, nriserEG commented on banner-with-cta/client.js
> +        Evergage.cashDom(`[data-evg-campaign-id="${context.campaign}"][data-evg-experience-id="${context.experience}"]`)
```suggestion
        Evergage.cashDom(`[data-evg-campaign-id=${context.campaign}][data-evg-experience-id=${context.experience}]`)
```
Revert back to original. Keep it consistent with syntax used in other templates

2020-12-02 02:57 UTC, nriserEG commented on banner-with-cta/client.js
> +})();
Remove extra line

2020-12-02 02:58 UTC, nriserEG commented on einstein-content-recommendations/client.js
> +})();
Remove extra line

2020-12-02 02:58 UTC, nriserEG commented on einstein-product-recommendations/client.js
> +})();
Remove extra line

2020-12-02 02:58 UTC, nriserEG commented on exit-intent-popup-with-email-capture/client.js
> +})();
Remove extra line

2020-12-02 02:58 UTC, nriserEG commented on exit-intent-popup/client.js
> +})();
Remove extra line

2020-12-02 03:50 UTC, nriserEG submitted a review, later dismissed
Looks good! Just delete the extra lines as noted in my comments 👍

2020-12-03 16:14 UTC, avkieu approved these changes
Security Approved

2020-12-15 05:11 UTC, merged