@W-8307462@ | Global Template Updates
evergage/evergage-global-templates pull request #28
Opened 2020-12-08 23:02 UTC by amaskiellEG

# Description

_TODO_

## Related Issues/Tickets

GUS: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008AbDzIAK/view

## How to test

_TODO_

#### Template:
- You can view the demo template in account:dataset, **template name: TEMPLATE_NAME**.

#### Campaign:
- You can view the demo campaign using this template in account:dataset, **campaign name: CAMPAIGN_NAME**
_Note: you will need to force the SDK using this URL: SDK_URL_

### Things to check for:
* **Visuals:** Does it look good across different client sites? To test this, you can copy, paste, and run this snippet in the JS console: GITHUB_GIST (see [template snippet](https://gist.github.com/nriserEG/fcfe7ab7e04d51dbf9cb19fc0476d474))
* **Mobile/smaller screen responsiveness:** Does the Template generally look good on smaller screens?
* **WCAG compliant:** Does the template contain ARIA attributes and/or use semantic elements for web accessibility? You can use the [WAVE Chrome extension tool](https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh) for a quick check.
* **Template-specific documentation**: Is there sufficient information for a Template Developer to use the Global Template and customize it for their own use?
* **FlickerDefender**: Is the page being fully hidden until the following page?
* **Campaign stats tracking:** Do impression stats and click stats fire for both the Control and Test experience?

2020-12-18 03:47 UTC, nriserEG requested changes
Noticed that the "Infobar With User Attribute & Call-To-Action" template name renders like this in the template list screen: 
<img width="445" alt="Screen Shot 2020-12-17 at 7 36 17 PM" src="https://user-images.githubusercontent.com/32201252/102572121-24b94a00-40a0-11eb-83bb-19c1741bcb7d.png">

Could you update the "&" to "and" in the .json file for now?

2020-12-18 03:47 UTC, nriserEG commented on exit-intent-popup/template.ts
>      ctaText: string ="Call To Action";
Could you make this minor update too?
```suggestion
    ctaText: string = "Call To Action";
```

2020-12-18 03:47 UTC, nriserEG commented on exit-intent-popup/template.ts
Could you make this minor update too on line 33?
`@title('CTA Destination URL')` --> `@title("CTA Destination URL")`

2020-12-18 03:47 UTC, nriserEG commented on infobar-with-cta/client.js
> +        return !!context.contentZone;
Control function can only return a Promise or void, and can't return a boolean. Just do what you did in apply()
```suggestion
        if (!context.contentZone) return;
```

2020-12-18 03:47 UTC, nriserEG commented on infobar-with-cta/template.ts
>      @title('CTA Destination URL')
Could you make this minor update too?
```suggestion
    @title("CTA Destination URL")
```

2020-12-18 03:47 UTC, nriserEG commented on infobar-with-cta/template.ts
>      @title('CTA Text')
Could you make this minor update too?
```suggestion
    @title("CTA Text")
```

2020-12-18 03:47 UTC, nriserEG commented on infobar-with-user-attribute-and-cta/template.ts
>      ctaUrl: string = "https://cumulusfinserv.com/banking";
Could you replace the single quotations with double quotations? throughout this file

2020-12-18 03:47 UTC, nriserEG commented on infobar-with-user-attribute-and-cta/client.js
> +        return !!context.contentZone;
Control function can only return a Promise or void, and can't return a boolean. Just do what you did in apply()
```suggestion
        if (!context.contentZone) return;
```

2021-01-04 22:15 UTC, amaskiellEG commented on exit-intent-popup/template.ts
>      ctaText: string ="Call To Action";
Lol How'd that happen? 🙃

2021-01-04 22:41 UTC, amaskiellEG commented on infobar-with-cta/client.js
> +        return !!context.contentZone;
Hmmmm where do you see that? I thought I had tested this before and it worked as expected 🤔 

I think I see what you're talking about when I check out the type definition for `control` [here](https://github.com/evergage/evergage-product/blob/e2c06a5ac7a207db6846b6bd42d5e6aa2e6e101f/analytics/excavator/src/main/resources/built-in/build/handlebars-templates/src/services/TemplateService.ts#L120), though I'm not sure that returning void would work here then?

2021-01-04 22:43 UTC, amaskiellEG commented on infobar-with-user-attribute-and-cta/client.js
> +        return !!context.contentZone;
https://github.com/evergage/evergage-global-templates/pull/28#discussion_r551612079

2021-01-04 22:50 UTC, nriserEG commented on infobar-with-cta/client.js
> +        return !!context.contentZone;
https://github.com/evergage/evergage-product/blob/e2c06a5ac7a207db6846b6bd42d5e6aa2e6e101f/analytics/excavator/src/main/resources/built-in/build/handlebars-templates/src/Template.ts

2021-01-05 18:47 UTC, amaskiellEG commented on infobar-with-cta/client.js
> +        return !!context.contentZone;
I just tested this out and neither the current code or your suggestion prevented the control stat from being sent when a content zone isn't selected; it seems like we actually need to do something like this:
```
return new Promise(resolve => { if (!!context.contentZone) resolve(!!context.contentZone); });
```

2021-01-06 02:18 UTC, nriserEG commented on infobar-with-cta/client.js
> +        return !!context.contentZone;
I looked at TemplateService.ts more closely, and actually, the reason why neither your original solution nor my suggested change works to block the control impression is due to the fact that void lands in the `else` statement, firing the control impression in the downstream anyway.
<img width="1287" alt="Screen Shot 2021-01-05 at 5 37 31 PM" src="https://user-images.githubusercontent.com/32201252/103719223-66416480-4f7d-11eb-88e6-f1fe73e1fb92.png">

I tried your new solution with the hanging Promise and that does seem to work 👍  I would simplify to the following:
`return new Promise(resolve => { if (context.contentZone) resolve(true) });`

2021-01-06 02:19 UTC, nriserEG commented on infobar-with-cta/client.js
> +        return new Promise(resolve => { if (!!context.contentZone) resolve(!!context.contentZone); });
```suggestion
        return new Promise(resolve => { if (context.contentZone) resolve(true) });
```

2021-01-06 02:20 UTC, nriserEG commented on infobar-with-user-attribute-and-cta/client.js
> +        return new Promise(resolve => { if (!!context.contentZone) resolve(!!context.contentZone); });
```suggestion
        return new Promise(resolve => { if (context.contentZone) resolve() });
```

2021-01-07 18:33 UTC, avkieu approved these changes
Security Approved

2021-01-07 20:01 UTC, nriserEG approved these changes
Approved!

Adding this note here too so we won't forget --
Since we're updating the "Infobar With User Attribute & Call-To-Action" template name, this template will be duplicated but with the new name. As such, we'll need to ask Oleg to manually remove the old template. This should be done at the same time this ticket is released. I'll coordinate with Oleg on this

2021-01-08 06:01 UTC, merged