W-8307520 | Einstein Decisions Banner
evergage/evergage-global-templates pull request #29
Opened 2021-02-19 17:00 UTC by amaskiellEG

# Description

This PR adds the Einstein Decisions Banner template.

## Related Issues/Tickets

GUS: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008AbHSIA0/view

**Promotion Assets:**
GUS: https://gus.lightning.force.com/lightning/r/ADM_Epic__c/a3QB000000013JLMAY/view
PR: https://github.com/evergage/evergage-product/pull/1906

## How to test

_TODO_ 🙃 

#### Template:
- You can view the demo template in eng3:andrewtest, **template name: W-8307520 | Einstein Decisions Banner (Context. Bandit)**.

#### Campaign:
- You can view the demo campaign using this template in account:dataset, **campaign name: CAMPAIGN_NAME**
_Note: you will need to force the SDK using this URL: https://eng3.devergage.com/beacon/eng3/andrewtest/scripts/evergage.min.js_

### Things to check for:
* **Visuals:** Does it look good across different client sites? To test this, you can copy, paste, and run this snippet in the JS console: GITHUB_GIST (see [template snippet](TODO)
* **Mobile/smaller screen responsiveness:** Does the Template generally look good on smaller screens?
* **WCAG compliant:** Does the template contain ARIA attributes and/or use semantic elements for web accessibility? You can use the [WAVE Chrome extension tool](https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh) for a quick check.
* **Template-specific documentation**: Is there sufficient information for a Template Developer to use the Global Template and customize it for their own use?
* **FlickerDefender**: Is the page being fully hidden until the following page?
* **Campaign stats tracking:** Do impression stats and click stats fire for both the Control and Test experience?

2021-02-25 06:53 UTC, nriserEG requested changes
Added review comments mostly related to wording and structure.

Also:
- Update comments in handlebars in general
- Needs a README
- Check the section on ADA compliance in this doc https://doc.evergage.com/display/EKB/Promotions#Promotions-AddADAComplianceFeaturestoPromotions, specifically regarding `alt-text`. That might be good enough, but see what else might make sense to do for ADA compliance.

2021-02-25 06:53 UTC, nriserEG commented on einstein-decisions/template.hbs
> +    2) Remove or change the default values for the configuration properties in Serverside Code.
Outdated

2021-02-25 06:53 UTC, nriserEG commented on einstein-decisions/template.ts
> +                promotion,
Remove ,

2021-02-25 06:53 UTC, nriserEG commented on einstein-decisions/template.ts
> +            };
unindent

2021-03-01 20:53 UTC, amaskiellEG commented on einstein-decisions/template.hbs
> +    3) Add any necessary image dimensions to the Serverside code.
We did 🙂  Sorry, I forgot to remove those!

2021-03-01 20:55 UTC, amaskiellEG commented on einstein-decisions/template.hbs
> +    Global Template: Einstein (Contextual Bandit) Promotions Banner
I'll check with Max, but I think it should be "Einstein Decisions Banner"? Once I hear from him, I'll change the related references to the name.

2021-03-02 04:16 UTC, nriserEG commented on einstein-decisions/template.hbs
> +    Global Template: Einstein Decisions
Saw Max's note here: https://docs.google.com/document/d/1PBkSmkVVYNZwgRtdGvhNYwwjzCaH0V_cHkfckwd-CdI/edit?disco=AAAALlSarpw 

Can you double check with him that we want Einstein Decisions and not Contextual Bandit like he has in his updated V1 comp?

2021-03-02 04:17 UTC, nriserEG commented on einstein-decisions/template.hbs
> +    Global Template: Einstein (Contextual Bandit) Promotions Banner
Saw Max's note here: https://docs.google.com/document/d/1PBkSmkVVYNZwgRtdGvhNYwwjzCaH0V_cHkfckwd-CdI/edit?disco=AAAALlSarpw

Can you double check with him that we want Einstein Decisions and not Contextual Bandit like he has in his V1 comp that he updated earlier today?

2021-03-02 04:31 UTC, nriserEG requested changes

2021-03-02 04:31 UTC, nriserEG commented on einstein-decisions/template.hbs
> +    1) Set the content zone(s) to that are defined in your Sitemap.
Double check: like https://github.com/evergage/evergage-global-templates/blob/master/banner-with-cta/template.hbs
```suggestion
    1) Set the content zone(s) to that defined in your Sitemap.
```

2021-03-02 04:31 UTC, nriserEG commented on einstein-decisions/template.ts
> +            };
Couldn't comment on the old thread but I think the one-liner looks best for this case 👍

2021-03-02 04:31 UTC, nriserEG commented on einstein-decisions/template.ts
> +            contentZone: context.contentZone,
Remove ,

2021-03-03 16:55 UTC, amaskiellEG commented on einstein-decisions/template.ts
> +
Awaiting a more complete assessment of what to do about that: https://evergage.slack.com/archives/CJDLXS8MT/p1614790095088500

2021-03-03 16:57 UTC, amaskiellEG commented on einstein-decisions/template.hbs
> +    1) Set the content zone(s) to that are defined in your Sitemap.
Is that really how the other ones are worded? Both of those don't read very well 😅

2021-03-03 17:06 UTC, amaskiellEG commented on einstein-decisions/template.hbs
> +    1) Set the content zone(s) to that are defined in your Sitemap.
Oh, I guess that's how it's written in the other ones; thanks for catching that 🙂

2021-03-03 18:04 UTC, amaskiellEG commented on einstein-decisions/template.hbs
> +    Global Template: Einstein Decisions
Checked with him, and yup, that's what he wants to call it (he commented in the doc that the mockup was old)

2021-03-03 19:22 UTC, amaskiellEG commented on einstein-decisions/template.ts
> +
We have an answer 🙂  https://evergage.slack.com/archives/CJDLXS8MT/p1614796161104000

2021-03-05 01:53 UTC, nriserEG requested changes
I don't think you read my comment here? https://github.com/evergage/evergage-global-templates/pull/29#pullrequestreview-598179176

> - Update comments in handlebars in general
> - Needs a README
> - Check the section on ADA compliance in this doc https://doc.evergage.com/display/EKB/Promotions#Promotions-AddADAComplianceFeaturestoPromotions, specifically regarding alt-text. That might be good enough, but see what else might make sense to do for ADA compliance.

Could you also address this? https://github.com/evergage/evergage-global-templates/pull/29#discussion_r582542734

> I think we should explain the setup in more detail (feature flag and setup on feature engineering page) but still brief. Similar to the explanation you wrote for SmartTrends https://developer.evergage.com/campaign-development/smart-apis/smart-trends

2021-03-05 01:53 UTC, nriserEG commented on einstein-decisions/template.ts
> +    forHeaderSubtitle;
Sigh. Too bad there's no other better solution for small italicized text. Are we against using readonly instead? I personally think it'd be better to use readonly than to use arbitrary props and decorators. It doesn't look too bad...? 
<img width="882" alt="Screen Shot 2021-03-04 at 5 37 27 PM" src="https://user-images.githubusercontent.com/32201252/110054626-4c6b9600-7d10-11eb-9c4a-349846753645.png">

2021-03-05 01:53 UTC, nriserEG commented on einstein-decisions/template.hbs
> +    This Global Template inserts a Promotion, chosen by an Einstein Decision (Contextual Bandit).
Let's just stick with the official name
```suggestion
    This Global Template inserts a Promotion, chosen by an Einstein Decisions.
```

2021-03-05 21:40 UTC, amaskiellEG commented on einstein-decisions/template.ts
> +    forHeaderSubtitle;
I think this is one for @mebb93; if we had to choose one, I'd probably choose the italicized text over the readonly, purely because of the extra line-spacing that comes with using readonly 😕

2021-03-05 21:43 UTC, amaskiellEG commented on einstein-decisions/template.hbs
> +    This Global Template inserts a Promotion, chosen by an Einstein Decision (Contextual Bandit).
Should probably check with @mebb93 about this too; we're only displaying one decision in the template, which is why I left the language "an Einstein Decision (Contextual Bandit).", but I'm open to changing it.

2021-03-05 21:44 UTC, amaskiellEG commented on einstein-decisions/template.hbs
> +    1) Remove or change the default values for the configuration properties in Serverside Code.
Well, they could technically add a Promotion filter if they wanted, though they'd have to be pretty creative/persistent in order to figure out how that works lol

But point taken: I'll change it 🙂

2021-03-05 21:54 UTC, amaskiellEG commented
@nriserEG Sorry, I missed your comments about the README; it seems like the slide-in template needs one as well, so how would you feel about having a separate ticket to add those?

2021-03-08 13:35 UTC, mebb93 commented on einstein-decisions/template.hbs
> +    Global Template: Einstein (Contextual Bandit) Promotions Banner
Template name should just be "Einstein Decisions"

2021-03-08 13:37 UTC, mebb93 commented on einstein-decisions/template.ts
> +    forHeaderSubtitle;
could you share a screenshot of what the italicized version looks like?

2021-03-08 13:39 UTC, mebb93 commented on einstein-decisions/template.hbs
> +    This Global Template inserts a Promotion, chosen by an Einstein Decision (Contextual Bandit).
should read "this global template inserts a promotion selected by Einstein Decisions". The feature itself is called Einstein Decisions so we don't need to differentiate that it is a "decision"

2021-03-08 15:10 UTC, amaskiellEG commented on einstein-decisions/template.hbs
> +    This Global Template inserts a Promotion, chosen by an Einstein Decision (Contextual Bandit).
@mebb93 - Sure!
![Screen Shot 2021-03-08 at 10 09 01 AM](https://user-images.githubusercontent.com/50626880/110339681-6cdc6e80-7ff6-11eb-80b3-17d10cb8bac1.png)

2021-03-08 15:10 UTC, amaskiellEG commented on einstein-decisions/template.ts
> +    forHeaderSubtitle;
@mebb93 - Sure!
![Screen Shot 2021-03-08 at 10 09 01 AM](https://user-images.githubusercontent.com/50626880/110339681-6cdc6e80-7ff6-11eb-80b3-17d10cb8bac1.png)

2021-03-08 15:13 UTC, mebb93 commented on einstein-decisions/template.ts
> +    forHeaderSubtitle;
I like it with that. Maybe add "no additional configuration required." after that sentence. The reason we might want it is if only one content zone is defined and a business user picks that template the config will show up totally blank in the campaign editor view and they might think something is broken.

2021-03-08 17:17 UTC, amaskiellEG commented on einstein-decisions/template.ts
> +    forHeaderSubtitle;
Hmmmm I think if we add something like that, then the sentence needs more context; maybe something like, "If this template only supports a singular content zone, then no additional configuration is required." ?

@nriserEG, @avkieu - thoughts?

2021-03-08 17:26 UTC, mebb93 commented on einstein-decisions/template.ts
> +    forHeaderSubtitle;
no need for the "no additional configuration required". the existing sentence "only offer assets..." works and makes sense even if the drop-down selector is not present

2021-03-09 21:11 UTC, nriserEG submitted a review, later dismissed

2021-03-11 03:34 UTC, nriserEG requested changes

2021-03-11 03:34 UTC, nriserEG commented on slide-in-with-cta/README.md
> +5. Post-Attribute Message Text
This isn't used in this template

2021-03-11 03:34 UTC, nriserEG commented on slide-in-with-cta/README.md
> +    - Second(s) of inactivity on page
```suggestion
    - Time on Page (Delay)
    - Scroll Depth
    - Inactivity
```

2021-03-11 22:16 UTC, amaskiellEG commented on slide-in-with-cta/README.md
> +5. Post-Attribute Message Text
Ohp, missed that one. Thanks :)

2021-03-11 22:17 UTC, amaskiellEG commented on slide-in-with-cta/README.md
> +    - Second(s) of inactivity on page
Lol I added the subtitles instead of the titles 🙃  Thanks for catching that!

2021-03-12 01:31 UTC, johnwatts approved these changes
Security review passes.

2021-03-12 01:40 UTC, nriserEG approved these changes

2021-03-16 16:53 UTC, amaskiellEG commented
Should only be released once [#1906](https://github.com/evergage/evergage-product/pull/1906) is released.

2021-05-14 18:20 UTC, merged