@W-9043924@ BUG | Fix control tracking for Redirect Global Template
evergage/evergage-global-templates pull request #30
Opened 2021-03-23 21:08 UTC by amaskiellEG

# Description

This PR ensures that control impressions are tracked for correctly in the Redirect template.

## Related Issues/Tickets

GUS: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH0000008v5YYAQ/view

## How to test
Account: `training`
Dataset: `amask`

**Campaign**: BUG W-9043924 | Redirect
**Template**: BUG W-9043924 | Redirect Test

NOTE: For ease of testing, I've left console.log statements in each of the Templates, which print the first text input field followed by the experience ID, since that is used in the `msreceiver`.

2021-03-23 21:12 UTC, avkieu requested changes

2021-03-23 21:12 UTC, avkieu commented on redirect/client.js
> +        Evergage.DisplayUtils.bind(`${campaign}:${experience}`).pageElementLoaded(contentZoneSelector).then(element => {
Since `apply` doesn't check for a loaded `contentZone`, I don't `control` should either? You can just send the stat.

2021-03-23 21:18 UTC, nriserEG commented on redirect/client.js
> +        Evergage.DisplayUtils.bind(`${campaign}:${experience}`).pageElementLoaded(contentZoneSelector).then(element => {
Wondering the same thing Alex brought up

2021-03-23 21:18 UTC, amaskiellEG commented on redirect/client.js
> +        Evergage.DisplayUtils.bind(`${campaign}:${experience}`).pageElementLoaded(contentZoneSelector).then(element => {
I thought about that as well, and you're right: we could probably just get away with sending the stat.

What I had in mind was only to send the stat if the `body` had loaded (since it could conceivably _not_ load with some newer JS frameworks....?)

If you think that's unnecessary though, I'm more than happy to just send the stat 🙂

2021-03-23 21:21 UTC, avkieu commented on redirect/client.js
> +        Evergage.DisplayUtils.bind(`${campaign}:${experience}`).pageElementLoaded(contentZoneSelector).then(element => {
For the same reason, the redirect doesn't care if the body loaded or not. It'd actually be nice if it happened before body loaded. So, do send the stat regardless of anything being loaded.

2021-03-23 21:24 UTC, amaskiellEG commented on redirect/client.js
> +        Evergage.DisplayUtils.bind(`${campaign}:${experience}`).pageElementLoaded(contentZoneSelector).then(element => {
Done! 🙂

2021-03-23 21:28 UTC, avkieu approved these changes

2021-03-23 21:36 UTC, nriserEG approved these changes

2021-03-25 16:08 UTC, amaskiellEG commented
This actually might not be a bug and what I was experiencing in the support ticket might have been presenting the issue incorrectly. Let's hold on releasing this until I can test a little bit further, since it seems like we should be sending an impression stat by default when there isn't a Campaign element.

2021-03-25 22:16 UTC, amaskiellEG commented
Ok yeah, I tested this more and am going to close this out.

Their issue was related to something else, which was unclear from the support ticket. Because of the way the template was behaving in their Campaign, I thought the empty `control` function might've had something to do with it.

That being said, it's definitely a little confusing that we send impressions for the control group by default if there isn't any code in the `control` function; it's been so long since I've worked with a template that _didn't_ have something in the `control` function, that my gut reaction to an empty `control` function was that it could be causing an issue. Maybe it's worth leaving a small comment in empty `control` functions as a reminder?

2021-03-25 22:16 UTC, closed without merging