@W-8307520@ Feature | Einstein Decisions Banner with FallbackArm
evergage/evergage-global-templates pull request #32
Opened 2021-05-06 23:38 UTC by amaskiellEG

# Description

This PR adds to the Einstein Decisions Banner template from #29, by implementing additional fallback options.

## Related Issues/Tickets

GUS: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008AbHSIA0/view

**Promotion Assets:**
GUS: https://gus.lightning.force.com/lightning/r/ADM_Epic__c/a3QB000000013JLMAY/view
PR: https://github.com/evergage/evergage-product/pull/1906

## How to test

#### Template:
- You can view the demo template in eng3:andrewtest, **template name: [AM Clone 2.0] W-8307520 | Einstein Decisions (with FallbackArm)**.

_TODO 🙃 _
#### Campaign:
- FYI: If you encounter issues, you _may_ have to reload the page a couple of times before the Campaign shows up. I experienced some odd results when trying to test, but I _think_ it might have to do with something like "the bandit needs more info about the user", "the server that serves up promotions needed to warm up", etc. but I'm not entirely sure.
- You can view demo Campaigns using this Template in eng3:andrewtest
**campaign name: W-8307520 | Einstein Decisions (home_hero)**
https://www.northerntrailoutfitters.com/default/homepage
**campaign name: W-8307520 | Einstein Decisions (home_sub_hero)**
https://www.northerntrailoutfitters.com/default/homepage?test=homeSubHero
**campaign name: W-8307520 | Einstein Decisions (category_hero)**
https://www.northerntrailoutfitters.com/default/women
https://www.northerntrailoutfitters.com/default/men
**campaign name: W-8307520 | Einstein Decisions (category_sub_hero)**
https://www.northerntrailoutfitters.com/default/women?test=categorySubHero
https://www.northerntrailoutfitters.com/default/men?test=categorySubHero

_Note: you will need to force the SDK using this URL: https://eng3.devergage.com/beacon/eng3/andrewtest/scripts/evergage.min.js_

### Things to check for:
* **Visuals:** Does it look good across different client sites? To test this, you can copy, paste, and run this snippet in the JS console: GITHUB_GIST (see [template snippet](https://gist.github.com/amaskiellEG/bd3aba9968251dd1a4aaf229690a6f49)
* **Mobile/smaller screen responsiveness:** Does the Template generally look good on smaller screens?
* **WCAG compliant:** Does the template contain ARIA attributes and/or use semantic elements for web accessibility? You can use the [WAVE Chrome extension tool](https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh) for a quick check.
* **Template-specific documentation**: Is there sufficient information for a Template Developer to use the Global Template and customize it for their own use?
* **FlickerDefender**: Is the page being fully hidden until the following page?
* **Campaign stats tracking:** Do impression stats and click stats fire for both the Control and Test experience?

2021-05-06 23:40 UTC, amaskiellEG commented on einstein-decisions/template.hbs
> +    5) Create and configure Promotions, either manually or through an ETL.
These are omitted from @aspatti1257's [template](https://eng3.devergage.com/ui/new-app/#/dataset/andrewtest/templates/edit/1BwZc/?channel=Web) but maybe that's because they were just added during code review of #29?

2021-05-06 23:42 UTC, amaskiellEG commented on einstein-decisions/template.ts
> +    @subtitle("Select a fallback promotion to display if there are no eligible promotions to show to the end user. If no fallback is selected, the default site experience would display. (NOTE: This f
I noticed this field is case-sensitive and it was... annoying, as an end-user. The note at the end that I added seems like a small way to go to prevent/alleviate some customer frustration for now.

2021-05-07 01:59 UTC, aspatti1257 reviewed
I think there's one small adjustment I didn't account for. Other than that curious as to your thoughts on whether we should show something if url is undefined or null.

2021-05-07 01:59 UTC, aspatti1257 commented on einstein-decisions/template.hbs
> +    5) Create and configure Promotions, either manually or through an ETL.
Yea I omitted 2 and 3 on purpose because:
2.) All NextGen customers have this account feature enabled by default.
3.) All new datasets as of 2-3 weeks ago have FeatureEngineering configured by default. And even if you don't you can still get bandit arms back as of this week.

That being said, there are loads of older customers transitioning over, or with older datasets. So in retrospect I think it actually makes sense to keep this the way you have it here.

2021-05-07 01:59 UTC, aspatti1257 commented on einstein-decisions/template.ts
> +    @subtitle("Select a fallback promotion to display if there are no eligible promotions to show to the end user. If no fallback is selected, the default site experience would display. (NOTE: This f
Agree. Our Angular item search isn't case-sensitive. This should not be either. Sounds like a feature enhancement/bug.

2021-05-07 01:59 UTC, aspatti1257 commented on slide-in-with-cta/README.md
> +### Slide-In with Call-to-Action
This is unrelated to bandit right? Intentional that it's part of this branch?

2021-05-07 01:59 UTC, aspatti1257 commented on einstein-decisions/README.md
> +1. Content Zone
Is this incomplete? Just has `1. Content Zone` and seems to stop after that?

2021-05-07 01:59 UTC, aspatti1257 commented on einstein-decisions/template.hbs
> +{{#if imageUrl}}
Open question: 

So if imageUrl is non-null, but url is null, should we allow this to render still? I say we have at least 3 options:
1.) Allow it to render anyways. Pretty much all promotions should have a url. So the risk of this is minimal.
2.) Does `{{#if imageUrl && url}}` work? Not sure if that's valid handlebars syntax.
3.) Default `url` to "/" in the server-side code. So even if it's not populated, clicking the promo will still take you back to the homepage.

This is all to protect a careless campaign dev of course. But if they screw it up support gets blasted. So it's worth solving here.

2021-05-07 01:59 UTC, aspatti1257 commented on einstein-decisions/template.ts
> +                        (this.fallbackAsset && asset.contentZones.includes(this.fallbackAsset))) {
Hmm, I just realized this but I think we should only do this if the returned arm IS the fallback promo. Otherwise, the following can happen:

You have a legit arm returned but a fallback arm configured, the legit arm happens to have 2 assets with one content zone each. Asset 1 has the the content zone for `context.contentZone`, which we would want to show in this case, asset 2 has the content zone for `this.fallbackAsset`.

So I think the final check looks something like:

`(this.fallbackArm && this.fallbackArm.id === promotion.id && this.fallbackAsset && asset.contentZones.includes(this.fallbackAsset))`

Thoughts?

2021-05-07 03:35 UTC, nriserEG requested changes

2021-05-07 03:35 UTC, nriserEG commented on einstein-decisions/template.ts
> +    @subtitle("Select a fallback promotion to display if there are no eligible promotions to show to the end user. If no fallback is selected, the default site experience would display. (NOTE: This f
Could we change the subtitle wording from "Select a...." to "Search for a..." or something since it's a search and not a lookup (also to match the wording of the placeholder)?

2021-05-07 03:35 UTC, nriserEG commented on slide-in-with-cta/README.md
> +### Slide-In with Call-to-Action
This entire content is the README for the slide in with cta global template

2021-05-07 03:35 UTC, nriserEG commented on einstein-decisions/template.hbs
> +{{#if imageUrl}}
I think we should just avoid rendering the generated HTML in the first place if `url` doesn't exist. We could add a `!context.url` check in the `if` statement that we already have at the top of the `apply` function in Clientside.

With that said, we could remove the {{#if ...}} handlebars expression since we'd check for both `imageUrl` and `url` in context already. That expression is better suited for conditionally rendering only parts of the content we want to render conditionally (like a subheader or the a lightbox in this [example](https://github.com/evergage/evergage-global-templates/blob/master/exit-intent-popup-with-email-capture/template.hbs), if the biz user chooses to show them)

2021-05-10 14:56 UTC, amaskiellEG commented on slide-in-with-cta/README.md
> +### Slide-In with Call-to-Action
@nriserEG, @aspatti1257 - It's in here because I branch from #29 and we decided to make a couple small changes to other READMEs we noticed: https://github.com/evergage/evergage-global-templates/pull/29#issuecomment-791735521

2021-05-10 15:01 UTC, amaskiellEG commented on einstein-decisions/template.hbs
> +{{#if imageUrl}}
Yeah, I agree with @nriserEG; it'd probably be best to just check for all of those values at the top of `apply`.

@aspatti1257 - Unfortunately, using logical operators like that in Handlebars isn't supported. There are some different ways to handle that logic but what I would typically do is to add a value to `context` in `apply` that represents that boolean:
```js
context.isPromotionValid = context.imageUrl && context.url;
```
and then in the Handlebars HTML:
```html
{{#if isPromotionValid }}
```

2021-05-10 15:04 UTC, amaskiellEG commented on einstein-decisions/template.ts
> +                        (this.fallbackAsset && asset.contentZones.includes(this.fallbackAsset))) {
Is there a reliable way to test that? If that's something we're going to change, then it might be helpful to have some steps I could follow, since I'm not sure I'd be able to readily determine if I was seeing what was expected or not.

2021-05-10 15:27 UTC, aspatti1257 commented on einstein-decisions/template.ts
> +                        (this.fallbackAsset && asset.contentZones.includes(this.fallbackAsset))) {
Yes, let me get back to you on the best ways to do this.

2021-05-10 17:44 UTC, nriserEG commented on slide-in-with-cta/README.md
> +### Slide-In with Call-to-Action
Oh that's right, totally forgot about that

2021-05-11 20:53 UTC, aspatti1257 commented
Update. This is now no-longer on hold. Please proceed with this as you were before. Greg confirmed that we won't need to make any additional API changes. @amaskiellEG , @nriserEG

2021-05-11 21:42 UTC, mebb93 commented on einstein-decisions/template.hbs
> +    for the dataset. Once again, please contact your account administrator if you encounter issues.
- Make the first requirement (before the content zones one) say "Einstein Decisions is an Interaction Studio premium edition feature and is not available to growth edition customers."
- replace items 2 & 3 with this line "Ensure that you have feature engineering set up via the Einstein Decisions tab in the left hand navigation of the platform. If you encounter issues, please contact your account administrator."

2021-05-12 12:20 UTC, amaskiellEG commented on einstein-decisions/template.ts
> +                        (this.fallbackAsset && asset.contentZones.includes(this.fallbackAsset))) {
> With the way it is here, when you get promo1 back, we'll show the asset for ContentZoneA. Even though it has an asset with ContentZoneB.

@aspatti1257 - I'm not sure that's the case based on my test? Would you mind checking that how I set this up is the same as what you had in mind?

**Promotions:**
PromoA: https://eng3.devergage.com/ui/index.html?_ak=eng3#/dataset/andrewtest/catalog/itemEdit?itemType=Promotion&itemId=FbmfP&timeRange=pastWeek&_ak=eng3
Promo B: https://eng3.devergage.com/ui/index.html?_ak=eng3#/dataset/andrewtest/catalog/itemEdit?itemType=Promotion&itemId=Njisu&timeRange=pastWeek&_ak=eng3

**Template:**
https://eng3.devergage.com/ui/new-app/#/dataset/andrewtest/templates/edit/QWx5l/?channel=Web

**Campaign:**
https://eng3.devergage.com/ui/new-app/#/dataset/andrewtest/campaigns/edit/YdIJl

**Test URL:**
https://www.northerntrailoutfitters.com/default/women?test=fallbackArmPR

2021-05-12 22:23 UTC, aspatti1257 commented on einstein-decisions/template.ts
> +                        (this.fallbackAsset && asset.contentZones.includes(this.fallbackAsset))) {
@amaskiellEG , that setup won't work because there aren't _two assets_ on each promo. Each one of those that you linked has one asset with two content zones. I'm thinking a setup more like this:

```
{
	"_id" : "i3mXb",
	"attributionMethod" : "SpecificItem",
	"au" : ISODate("2021-05-12T22:12:50.956Z"),
	"c" : ISODate("2021-05-10T17:30:31.941Z"),
	"expiration" : null,
	"locked" : false,
	"name" : "test Promo B",
	"pcbIds" : [ ],
	"piName" : "",
	"promotionState" : null,
	"published" : null,
	"seg" : null,
	"type" : "P",
	"u" : ISODate("2021-05-12T22:12:50.956Z"),
	"url" : "test promo B",
	"assets" : [
		{
			"type" : "CdnImage",
			"id" : "qAOs9",
			"contentZones" : [
				"Homepage | Sub Hero"
			],
			"created" : ISODate("2021-05-10T17:30:31.967Z"),
			"updated" : ISODate("2021-05-10T17:34:20.474Z"),
			"imageUrl" : "https://s3.amazonaws.com/evergage-promotions-dev/promotions/localtest/dev/i3mXb/qAOs9.png",
			"format" : "PNG"
		},
		{
			"type" : "CdnImage",
			"id" : "iN07y",
			"contentZones" : [
				"Homepage | Hero"
			],
			"created" : ISODate("2021-05-10T17:40:33.465Z"),
			"updated" : ISODate("2021-05-12T22:12:50.956Z"),
			"imageUrl" : "https://s3.amazonaws.com/evergage-promotions-dev/promotions/localtest/dev/i3mXb/iN07y.png",
			"format" : "PNG"
		}
	],
	"allTimeStats" : {
		"efs" : 178,
		"rfs" : 178,
		"se" : 88
	},
	"attributes" : {
		"archived" : {
			"name" : "archived",
			"value" : false,
			"updated" : ISODate("2021-05-10T17:30:56.648Z")
		},
		"attributionMethod" : {
			"name" : "attributionMethod",
			"value" : "SpecificItem",
			"updated" : ISODate("2021-05-10T17:30:56.648Z")
		},
		"name" : {
			"name" : "name",
			"value" : "test Promo B",
			"updated" : ISODate("2021-05-10T17:30:56.648Z")
		},
		"promotable" : {
			"name" : "promotable",
			"value" : true,
			"updated" : ISODate("2021-05-10T17:30:56.648Z")
		},
		"promotedItemName" : {
			"name" : "promotedItemName",
			"value" : "",
			"updated" : ISODate("2021-05-10T17:30:56.648Z")
		},
		"url" : {
			"name" : "url",
			"value" : "test promo B",
			"updated" : ISODate("2021-05-10T17:30:56.648Z")
		}
	},
	"dailyStats" : [
		{
			"date" : ISODate("2021-05-10T00:00:00Z"),
			"rfs" : 178,
			"efs" : 178,
			"se" : 88
		}
	],
	"custom" : {
		"archived" : "false",
		"promotable" : "true",
		"name" : "test Promo B",
		"promotedItemName" : null,
		"attributionMethod" : "SpecificItem",
		"url" : "test promo B"
	}
}
```
and:
```
{
	"_id" : "W5NxR",
	"attributionMethod" : "SpecificItem",
	"au" : ISODate("2021-05-12T22:12:29.704Z"),
	"c" : ISODate("2021-05-10T17:24:05.166Z"),
	"expiration" : null,
	"locked" : false,
	"name" : "test Promo A",
	"pcbIds" : [ ],
	"piName" : "",
	"promotionState" : null,
	"published" : null,
	"seg" : null,
	"type" : "P",
	"u" : ISODate("2021-05-12T22:12:29.705Z"),
	"url" : "test promo A",
	"assets" : [
		{
			"type" : "CdnImage",
			"id" : "Lv0ME",
			"contentZones" : [
				"Homepage | Sub Hero"
			],
			"created" : ISODate("2021-05-10T17:24:05.266Z"),
			"updated" : ISODate("2021-05-10T17:34:02.620Z"),
			"imageUrl" : "https://s3.amazonaws.com/evergage-promotions-dev/promotions/localtest/dev/W5NxR/Lv0ME.png",
			"format" : "PNG"
		},
		{
			"type" : "CdnImage",
			"id" : "5mCeB",
			"contentZones" : [
				"Homepage | Hero"
			],
			"created" : ISODate("2021-05-10T17:38:51.177Z"),
			"updated" : ISODate("2021-05-12T22:12:28.146Z"),
			"imageUrl" : "https://s3.amazonaws.com/evergage-promotions-dev/promotions/localtest/dev/W5NxR/5mCeB.png",
			"format" : "PNG"
		}
	],
	"allTimeStats" : {
		"efs" : 189,
		"rfs" : 189,
		"se" : 89
	},
	"dailyStats" : [
		{
			"date" : ISODate("2021-05-10T00:00:00Z"),
			"rfs" : 189,
			"efs" : 189,
			"se" : 89
		}
	],
	"attributes" : {
		"archived" : {
			"name" : "archived",
			"value" : false,
			"updated" : ISODate("2021-05-10T17:25:24.768Z")
		},
		"attributionMethod" : {
			"name" : "attributionMethod",
			"value" : "SpecificItem",
			"updated" : ISODate("2021-05-10T17:25:24.768Z")
		},
		"name" : {
			"name" : "name",
			"value" : "test Promo A",
			"updated" : ISODate("2021-05-10T17:25:24.768Z")
		},
		"promotable" : {
			"name" : "promotable",
			"value" : true,
			"updated" : ISODate("2021-05-10T17:25:24.768Z")
		},
		"promotedItemName" : {
			"name" : "promotedItemName",
			"value" : "",
			"updated" : ISODate("2021-05-10T17:25:24.768Z")
		},
		"url" : {
			"name" : "url",
			"value" : "test promo A",
			"updated" : ISODate("2021-05-10T17:25:24.768Z")
		}
	},
	"custom" : {
		"archived" : "false",
		"promotable" : "true",
		"name" : "test Promo A",
		"promotedItemName" : null,
		"attributionMethod" : "SpecificItem",
		"url" : "test promo A"
	}
}
```
(these are what I was using to test locally, feel free to just pop them into a local dataset if you have it setup (pull master). The general idea is you want two assets PER promotion. And each asset has one content zone). Apologies for not being more clear.


Anyways, you should be able to get it to the state where you are returning a promotion with `context.contentZone` (i.e. what's configured in the template's lower left panel), but because of the way the fallback is configured, you'll be showing the asset that has that of `context.fallbackAsset` (i.e. what's configured as the backup, in the template's left panel). We'll probably need something similar to what I posted above 2 days ago, in order to make sure we don't show the wrong asset.

2021-05-12 22:25 UTC, aspatti1257 commented on einstein-decisions/template.ts
> +                        (this.fallbackAsset && asset.contentZones.includes(this.fallbackAsset))) {
Also, eng3 has been wonky for me as of late. So I prefer to test this locally. If you can get the VE to run well and it's not trying to direct traffic to `:8443` urls cause it thinks it's on a local cluster, and you prefer to use eng3, be my guest.

2021-05-13 18:48 UTC, amaskiellEG commented on einstein-decisions/template.ts
> +                        (this.fallbackAsset && asset.contentZones.includes(this.fallbackAsset))) {
Talked about this on a Meet call; the changes we agreed upon to handle this case can be found in [this commit](https://github.com/evergage/evergage-global-templates/pull/32/commits/497c11b402659b0bd97730c49ceaba117c16256f)

2021-05-13 20:31 UTC, aspatti1257 requested changes
Seems fine but I think we should add an `is ImageAsset` check in the fallback asset dropdown. (Sorry, just realized this was an issue)

Also, here's what I was thinking for an extractable function:

```

        const fetchImageUrl = (promotion: Promotion, contentZone: string): string => {
            if (!promotion || !promotion.assets) {
                return "";
            }
            for (const asset of promotion.assets) {
                if (!(asset.type === "CdnImage" || asset.type === "ExternalImage")) continue;
                if (asset.contentZones?.includes(contentZone)) {
                    return (asset as ImageAsset).imageUrl;
                }
            }
            if (this.fallbackAsset && this.fallbackArm?.id === promotion.id) {
                for (const asset of promotion.assets) {
                    if (!(asset.type === "CdnImage" || asset.type === "ExternalImage")) continue;
                    if (asset.contentZones?.includes(this.fallbackAsset)) {
                        return (asset as ImageAsset).imageUrl;
                    }
                }
            }
            return "";
        }

        const imageUrl: string = fetchImageUrl(promotion, context.contentZone);
        const url: string = promotion?.attributes?.url ? promotion.attributes.url.value as string : "";
```

I like that this lets us avoid having to use `let` when we can just declare something as immutable right off the bat. Not sure how it adheres to best practices established in other global templates though.

2021-05-13 20:31 UTC, aspatti1257 commented on einstein-decisions/template.ts
> +                for (const innerAsset of promotion.assets) {
minor: why `innerAsset`? What makes this asset `inner`?

2021-05-13 20:31 UTC, aspatti1257 commented on einstein-decisions/template.ts
> +            if (asset && asset.contentZones) {
Just realized: It doesn't matter yet cause we don't have DataAsset support. But I think we should add the check for CdnImage/ExternalImage here too (`asset.type === "CdnImage" || asset.type === "ExternalImage"`). Otherwise in the future someone with a stale global template can end configuring a DataAsset's content zone (which doesn't have an `imageUrl`) as the fallback arm.

2021-05-13 21:12 UTC, nriserEG requested changes
Only minor fixes

2021-05-14 14:11 UTC, aspatti1257 commented on einstein-decisions/template.ts
> +            if (asset && asset.contentZones) {
minor: Also, the `asset.type === "CdnImage" || asset.type === "ExternalImage"` is used at least 2 times in this template. May be worth making a small function out of.

2021-05-14 14:15 UTC, amaskiellEG commented on einstein-decisions/template.ts
> +                for (const innerAsset of promotion.assets) {
I was just trying to differentiate it from the other loop; they could both be called `asset` without issue but seems like the kind of thing that invites trouble, you know? 😅

2021-05-14 14:29 UTC, johnwatts submitted a review, later dismissed
Security review passes.

2021-05-14 14:58 UTC, amaskiellEG commented on einstein-decisions/template.ts
> +            if (asset && asset.contentZones) {
@aspatti1257 - So are you suggesting that the conditional should contain all of this logic?
```ts
asset && asset.contentZones && (asset.type === "CdnImage" || asset.type === "ExternalImage")
```

2021-05-14 15:00 UTC, amaskiellEG commented on einstein-decisions/template.ts
> +                for (const innerAsset of promotion.assets) {
I'm just being overly cautious; we should just call it `asset` 🙂

2021-05-14 15:07 UTC, aspatti1257 commented on einstein-decisions/template.ts
> +            if (asset && asset.contentZones) {
Yes. In the future we don't want to have a Data Asset's content zone as the eligible fallback for this web template's asset. This whole template is predicated around expecting an `imageUrl` so we'll be ignoring `data`.

2021-05-14 15:09 UTC, amaskiellEG commented on einstein-decisions/template.ts
> +            if (asset && asset.contentZones) {
Ah ok, perfect. Based on that, I'm just going to check for the asset type first.

2021-05-14 15:14 UTC, johnwatts submitted a review, later dismissed
Still secure.

2021-05-14 15:28 UTC, aspatti1257 requested changes
One last change because it looks like there's a compilation error now:

![image](https://user-images.githubusercontent.com/8547933/118293264-788d5b00-b4a7-11eb-9274-3eaf1acf746b.png)

2021-05-14 15:28 UTC, aspatti1257 commented on einstein-decisions/template.ts
> +        let url: string = promotion?.attributes?.url ? promotion.attributes.url as string : "";
Should be `url.value as string`. As in my original comment.

Also, do these need to be `let`s or can they be `const`s? They're immutable right?

2021-05-14 15:28 UTC, aspatti1257 commented on einstein-decisions/template.ts
> +function isCdnOrExternalImage(asset) {
minor: May want to add a type declaration for consistency:

`asset: Asset`

2021-05-14 15:33 UTC, amaskiellEG commented on einstein-decisions/template.ts
> +function isCdnOrExternalImage(asset) {
Good call 🙂  I think it might need to be `asset?: Asset` because of how it's used in the context of one of the iterators. I'll make sure it compiles in here, though: https://training.us-1.evergage.com/ui/new-app/#/dataset/amask_templates/templates/edit/9witi/?channel=Web

2021-05-14 15:52 UTC, aspatti1257 approved these changes
`template.ts` looks good. Will wait for @nriserEG 's final approval on the other components.

2021-05-14 15:52 UTC, aspatti1257 commented on einstein-decisions/template.ts
> +    forHeaderSubtitle;
Minor, there's a compiler warning (not error) when I hover over this untyped declaration. But if this is the precedent set by other templates let's keep it.

![image](https://user-images.githubusercontent.com/8547933/118296262-c48dcf00-b4aa-11eb-997e-bae20033eb33.png)

2021-05-14 17:11 UTC, nriserEG approved these changes

2021-05-14 18:20 UTC, merged