W-8306386 - Manual Promotion Template
evergage/evergage-global-templates pull request #34
Opened 2021-05-20 20:00 UTC by aspatti1257

# Description

Manual Promotion Selector for web.
- Only uses ImageAssets
- Mostly copied from the [existing draft](https://eng3.devergage.com/ui/new-app/#/dataset/andrewtest/templates/edit/sTbjS/?channel=Web) and the now released Einstein Decisions template). Removes all references to "Einstein " or "Decisions".

This also fixes a bug in 

## Related Issues/Tickets

GUS: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008AaFaIAK/view

## How to test

#### Template:
- You can view the demo template in `eng3:andrewtest`, **template name: [W-8306386 - Manual Promotion Selector [AP Draft]](https://eng3.devergage.com/ui/new-app/#/dataset/andrewtest/templates/edit/TPw8O/?channel=Web)**.

#### Campaign:
- You can view the demo campaign using this template in `eng3:andrewtest`, **campaign name: [https://eng3.devergage.com/ui/new-app/#/dataset/andrewtest/campaigns/edit/bkZjL](https://eng3.devergage.com/ui/new-app/#/dataset/andrewtest/campaigns/edit/bkZjL)**
_Note: forcing SDK URL doesn't seem to work well on eng3 as of late. I have not fully investigated why this is._

I recommend importing the template locally and testing via that account. If you don't have promotions, add ExternalImages, not CdnImages as you likely don't have the prod S3 creds necessary.

### Things to check for:
* **Visuals:** Does it look good across different client sites? To test this, you can copy, paste, and run this snippet in the JS console: GITHUB_GIST (see [template snippet](https://gist.github.com/nriserEG/fcfe7ab7e04d51dbf9cb19fc0476d474))
* **Mobile/smaller screen responsiveness:** Does the Template generally look good on smaller screens?
* **WCAG compliant:** Does the template contain ARIA attributes and/or use semantic elements for web accessibility? You can use the [WAVE Chrome extension tool](https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh) for a quick check.
* **Template-specific documentation**: Is there sufficient information for a Template Developer to use the Global Template and customize it for their own use?
* **FlickerDefender**: Is the page being fully hidden until the following page?
* **Campaign stats tracking:** Do impression stats and click stats fire for both the Control and Test experience?

2021-05-21 03:13 UTC, nriserEG requested changes

2021-05-21 15:04 UTC, aspatti1257 commented on manual-promotion/template.ts
> +    @subtitle("Select the promotion that you want to display in the targeted web content zone")
Done and updated the `config.png` to reflect the period.

2021-05-21 15:06 UTC, aspatti1257 commented on manual-promotion/evergage-template.json
> +  "name" : "Manual Promotion",
I think it should be "Manual Promotion Selector". Good point. Updated it everywhere I found it inconsistent.

2021-05-21 15:06 UTC, aspatti1257 commented on manual-promotion/template.hbs
> +        <img class="mcis-promotion-img" src="{{imageUrl}}">
Nah that's good feedback and easy.

2021-05-21 15:07 UTC, aspatti1257 commented on manual-promotion/template.css
> +}
Good point cause this totally didn't match the classes declared on the handlebars.

2021-05-21 15:14 UTC, aspatti1257 commented on manual-promotion/template.hbs
> +    1) Remove or change the default values for the configuration properties in Serverside Code.
Added another sentence, let me know if you want further revisions to this or we should update the Einstein Decisions template:
https://github.com/evergage/evergage-global-templates/pull/34/commits/dd155cdc6eee4f1375bef24ac0edfe0255d39ab0

2021-05-21 15:14 UTC, aspatti1257 commented on manual-promotion/template.ts
> +        }
Done for both.

2021-05-21 15:14 UTC, aspatti1257 commented on manual-promotion/template.ts
> +        const promotion: Promotion= context.services.catalog.findItem("Promotion", this.selectedPromo.id) as Promotion;
Doh, totally missed this one. Good catch.

2021-05-21 16:23 UTC, amaskiellEG submitted a review, later dismissed
@aspatti1257 - Looks mostly good to me! Just a couple of small things.

Also, I just want to make sure about this: if the selected `contentZone` doesn't exist on the page, the template shouldn't try to use the zone from the `selectedAsset`, right? If you _do_ want to have the `selectedAsset` be considered, maybe you could do something like this in the clientside code?
```js
const contentZoneSelector = Evergage.getContentZoneSelector(context.contentZone);
if (context.selectedAsset) {
    const selectedAssetSelector = Evergage.getContentZoneSelector(context.selectedAsset);
}
const combinedSelector = `${contentZoneSelector}${selectedAssetSelector ? `, ${selectedAssetSelector}` : ''}`;

return Evergage.DisplayUtils
    .bind(buildBindId(context))
    .pageElementLoaded(combinedSelector)
    .then((element) => {
        const html = template(context);
        Evergage.cashDom(element).html(html);
    });
```
(or switch the order of the selectors, based on whichever should take priority)

2021-05-21 18:26 UTC, nriserEG commented on manual-promotion/template.hbs
> +        <img class="mcis-promotion-img" src="{{imageUrl}}">
@aspatti1257  Oh I think I meant to add the note on scope creep for a different comment haha. Thanks for the update though. Yeah ideally we update the one for Einstein Decisions too in this PR

2021-05-21 18:51 UTC, nriserEG commented on manual-promotion-selector/template.ts
> +              "targeted web content zone.")
Agreed, just like https://github.com/evergage/evergage-global-templates/blob/master/einstein-decisions/template.ts

2021-05-21 18:53 UTC, nriserEG commented on manual-promotion-selector/template.hbs
> +    ability to chose the specific promotion and the specific asset you would like the end user to see.
typo
```suggestion
    ability to choose the specific promotion and the specific asset you would like the end user to see.
```

2021-05-21 20:57 UTC, aspatti1257 commented on einstein-decisions/template.ts
> +        const imageUrl: string = fetchImageUrl(promotion, context.contentZone, this.fallbackArm, this.fallbackAsset);
I'm pretty convinced it's a problem. Try the following template:

```
export class NewTemplate implements CampaignTemplateComponent {

    @title("Example Field")
    header: string;

    run(context: CampaignComponentContext) {
        function thisTest() {
            try {
                console.log(this.header);
            } catch(e) {
                return "failure"
            }
            
            return "success";
        }


        return {
            thisTest: thisTest()
        };
    }

}
```
(fails for me on master)

I think we tested before I mentioned that we should extract the method out. And it only worked after cause we never hit that part of the function that referenced `this`. We returned earlier than that.

2021-05-21 21:11 UTC, aspatti1257 commented
> @aspatti1257 - Looks mostly good to me! Just a couple of small things.
> 
> Also, I just want to make sure about this: if the selected `contentZone` doesn't exist on the page, the template shouldn't try to use the zone from the `selectedAsset`, right? If you _do_ want to have the `selectedAsset` be considered, maybe you could do something like this in the clientside code?
> 
> ```js
> const contentZoneSelector = Evergage.getContentZoneSelector(context.contentZone);
> if (context.selectedAsset) {
>     const selectedAssetSelector = Evergage.getContentZoneSelector(context.selectedAsset);
> }
> const combinedSelector = `${contentZoneSelector}${selectedAssetSelector ? `, ${selectedAssetSelector}` : ''}`;
> 
> return Evergage.DisplayUtils
>     .bind(buildBindId(context))
>     .pageElementLoaded(combinedSelector)
>     .then((element) => {
>         const html = template(context);
>         Evergage.cashDom(element).html(html);
>     });
> ```
> 
> (or switch the order of the selectors, based on whichever should take priority)

@amaskiellEG , good question. @mebb93 pinged me about this just before he went on vacation and here's our convo below:

![image](https://user-images.githubusercontent.com/8547933/119198234-fa0c5c80-ba56-11eb-906b-aaa4cad02001.png)

Essentially we don't want to restrict that for them. If they explicitly want to override and show a promotion asset with a content zone that is not on the page, let them. It shouldn't affect our reporting in any meaningful way. This is also why the server-side code explicitly checks the `this.selectedAsset` _before_ `context.contentZone`.

2021-05-21 21:13 UTC, aspatti1257 commented on manual-promotion-selector/template.ts
> +              "targeted web content zone.")
Applied your suggestion directly via the "Commit Suggestion" button but the indenting here doesn't match what's in the decisions template.

Bandit:
![image](https://user-images.githubusercontent.com/8547933/119198698-c4b43e80-ba57-11eb-828b-a089d5fbe670.png)

Manual promo:
![image](https://user-images.githubusercontent.com/8547933/119198721-cf6ed380-ba57-11eb-9ccb-4f0545ed452e.png)

Which is preferred?

2021-05-21 21:48 UTC, amaskiellEG commented
I'm not sure that conversation actually answers the scenario I had in mind...

Consider:
- `context.contentZone = "home_sub_hero"`
- `context.selectedAsset = "home_hero"`

Let's say that the template is running on the homepage and for some reason or another the selector associated with `"home_sub_hero"` doesn't match any elements on the page. _However, the selector for `"home_hero"` does._

My question is: if in a case like this one, do we then use the matching element for `"home_hero"` or do we simply show nothing because we couldn't find an element that matched the selector for `"home_sub_hero"`?

2021-05-21 21:52 UTC, amaskiellEG commented on manual-promotion-selector/template.ts
> +              "targeted web content zone.")
I actually kinda like the promo indentation more 😬  But either is fine with me, really 🤷‍♂️

2021-05-21 22:01 UTC, amaskiellEG commented on einstein-decisions/template.ts
> +        const imageUrl: string = fetchImageUrl(promotion, context.contentZone, this.fallbackArm, this.fallbackAsset);
So `this` is `null` if you use `function` to declare the function but it's fine if you use `const` and a fat-arrow function, since the fat-arrow function uses the previous-level-scope-definition for `this`:
![Screen Shot 2021-05-21 at 5 57 02 PM](https://user-images.githubusercontent.com/50626880/119202026-fcbe8000-ba5d-11eb-8ce2-bf789cacf8b9.png)
(in case I didn't describe it correctly/coherently: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#arrow_functions_used_as_methods)

2021-05-21 22:10 UTC, aspatti1257 commented
> I'm not sure that conversation actually answers the scenario I had in mind...
> 
> Consider:
> 
> * `context.contentZone = "home_sub_hero"`
> * `context.selectedAsset = "home_hero"`
> 
> Let's say that the template is running on the homepage and for some reason or another the selector associated with `"home_sub_hero"` doesn't match any elements on the page. _However, the selector for `"home_hero"` does._
> 
> My question is: if in a case like this one, do we then use the matching element for `"home_hero"` or do we simply show nothing because we couldn't find an element that matched the selector for `"home_sub_hero"`?

I see what you're saying. Yea I think we should allow them to fill in `context.selectedAsset`'s content zone if it's on the page, even if `context.contentZone` isn't. Will make the fix to the client side code for this.

2021-05-21 22:32 UTC, nriserEG commented on manual-promotion-selector/template.ts
> +              "targeted web content zone.")
yeah indented one looks better

2021-05-25 17:45 UTC, nriserEG approved these changes
Looks good. Tested with multiple promotions and assets, and validated different scenarios including one where the selector for context.contentZone doesn't exist on the page. This works as intended, as it resorts to using the selector for context.selectedAsset. If neither context.contentZone nor context.selectedAsset has an associated selector on the page, then the template will not render.

2021-05-26 14:17 UTC, amaskiellEG approved these changes
@aspatti1257 - I think the way you handled the `contentZone`/`selectedAsset` situation in client JS is better than what I suggested. This all looks good! 🎉

2021-05-26 20:00 UTC, astral303 approved these changes
Security review approved.

2021-05-26 20:01 UTC, merged