@W-9696080@ update global template namespace
evergage/evergage-global-templates pull request #37
Opened 2021-10-20 14:19 UTC by dchouEG

# Description

## Related Issues/Tickets

## How to test

#### Template:
- You can view the demo template in eng7:globaltemplate
- [SalesforceInteraction Global Templates](https://eng7.devergage.com/ui/index.html?_ak=eng7#/dataset/globaltemplates/campaigns/listV2?view=Traffic&campaignTypes=Web&folderIds=mbN6n&attributionWindow=defaultMax&timeFrame=Campaign&timeRange=pastWeek&_ak=eng7)

#### Campaign:
- You can view the demo campaign using this template in account:dataset, **campaign name: CAMPAIGN_NAME**
_Note: you will need to force the SDK using this URL: SDK_URL_

11 campaigns for Evergage namespace and 11 campaigns for SalesforceInteraction's name space were created on eng7 link above built using the branch: feature-unified-web-sdk-IS-Module-combined-testing

- An MVP of each templates were created for the homepage of NTO: https://www.northerntrailoutfitters.com/default/homepage
- Tested each MVP to ensure they display properly.
- Tested each MVP to ensure they attribute campaign stats properly.
- Tested each MVP to ensure recipes, promotions, other custom attributes were displayed.

2021-10-21 15:35 UTC, aschindlerEG submitted a review, later dismissed
These all look good to me. Tested a few just to see as well, and everything works as expected.

2021-11-03 13:38 UTC, dchouEG commented
> Are we totally removing global templates that have the old namespace? If so, is there a plan to document how those on the old namespace can make use of global templates that have the new namespace?

The global templates works with the evergage namespace and salesforceinteractions namespace, even when mixing and matching for backwards compatibility. There are no structural change outside of the namespace changes.

2021-11-09 00:53 UTC, aspatti1257 commented
If you're updating this to not rely on the "Evergage" namespace, why do all the DOM node attributes still have:
`data-evg-campaign-id`, etc in them?

Wouldn't this require an associated update to this and the handlebars gear in the product repo? Or is that out of scope for this PR and we're going to just stick with "evg" in the long term?

2021-11-12 22:08 UTC, amaskiellEG commented
> > Are we totally removing global templates that have the old namespace? If so, is there a plan to document how those on the old namespace can make use of global templates that have the new namespace?
> 
> The global templates works with the evergage namespace and salesforceinteractions namespace, even when mixing and matching for backwards compatibility. There are no structural change outside of the namespace changes.

Can you elaborate a little more about how to test this for the old namespace? I was hoping to test the campaigns in eng7 but I don't have credentials for it 😕  Can someone from the optimize team help me with getting credentials for that environment or is it something I'll have to request through the ops team?

2021-12-01 17:58 UTC, dchouEG commented
> If you're updating this to not rely on the "Evergage" namespace, why do all the DOM node attributes still have: `data-evg-campaign-id`, etc in them?
> 
> Wouldn't this require an associated update to this and the handlebars gear in the product repo? Or is that out of scope for this PR and we're going to just stick with "evg" in the long term?

It's out of scope

2021-12-01 22:11 UTC, amaskiellEG approved these changes
These changes look good to me 🙂 

I _did_ leave a couple of comments about things that I think we probably should take the time to change, but they're relatively minor and certainly not release-blocking.

2021-12-01 22:11 UTC, amaskiellEG commented on exit-intent-popup-with-email-capture/client.js
> +                SalesforceInteractions.sendEvent({
I'm kind of surprised we didn't include a default action name before. Maybe now would be a good chance to add one?

2021-12-01 22:11 UTC, amaskiellEG commented on slide-in-with-cta/client.js
> +        SalesforceInteractions.cashDom("#evg-slide-in-with-cta").remove();
I can't remember why we decided to use the ID instead of the more particular selector (i.e. like `[data-evg-campaign-id="${context.campaign}"][data-evg-experience-id="${context.experience}"]` used in other templates like the Manual Promo Selector).

However, now might be a good time to make that change for the slide-in.

2021-12-17 14:41 UTC, dchouEG commented on exit-intent-popup-with-email-capture/client.js
> +                SalesforceInteractions.sendEvent({
what should the default action name be?

2021-12-17 14:49 UTC, dchouEG commented on exit-intent-popup-with-email-capture/client.js
> +                SalesforceInteractions.sendEvent({
would `exit intent email capture` be good?

2021-12-17 17:06 UTC, amaskiellEG requested changes
@dchouEG - One small question 🙂

2021-12-17 17:06 UTC, amaskiellEG commented on exit-intent-popup-with-email-capture/client.js
>                  });
The name of the action looks ok to me, but shouldn't it be in `interaction` instead?
```js
SalesforceInteractions.sendEvent({
    interaction: {
        name: "Exit Intent Email Capture"
    },
    user: {
        attributes: {
            emailAddress: emailAddress
        }
    }
});
```

If we _are_ allowing for sending actions in the `user`, then this looks good to me 🙂

2021-12-17 18:02 UTC, dchouEG commented on exit-intent-popup-with-email-capture/client.js
>                  });
Oops! Brain fart, thanks for catching that!!

2021-12-28 21:44 UTC, amaskiellEG approved these changes
@dchouEG - Looks good! 👍 🎉 🌮

2022-03-03 20:18 UTC, theKevinRobertsExperience approved these changes

2022-03-09 22:34 UTC, merged