@W-10729767@ - Add journey-builder global template
evergage/evergage-global-templates pull request #40
Opened 2022-03-08 19:38 UTC by theKevinRobertsExperience

# Description

Adds a Journey Builder Global Template

## Related Issues/Tickets

GUS: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000qZD2tYAG/view

## How to test

Template can be demoed in `eng8:engage` and can be tested against both the "CDMHg" triggered campaign ID and "FNFDf" Server-Side campaign ID

2022-03-08 19:55 UTC, nriserEG commented on journey-builder/README.md
> +This is a Server Global Template. When used in a Trigger Campaign it reutnrs Trigger_Type and depending on the trigger type, it also can include Trigger_Segment, Trigger_Action, and Trigger_Catalog_I
```suggestion
When used in a Trigger Campaign, this Server-Side global template returns a Trigger_Type field. Depending on the trigger type, it also can include Trigger_Segment, Trigger_Action, and Trigger_Catalog_Items fields along with other information chosen by the Campaign Developer.
```

2022-03-08 20:02 UTC, nriserEG commented on journey-builder/template.ts
> +    @headerSubtitle("By default, the trigger includes the ContactKey and Trigger_Type fields. Depending on the trigger type, it also can include Trigger_Segment, Trigger_Action, and Trigger_Catalog_I
```suggestion
    @headerSubtitle("By default, the trigger includes the ContactKey and Trigger_Type fields. Depending on the trigger type, it could also include Trigger_Segment, Trigger_Action, and Trigger_Catalog_Items fields. Create these fields in your Marketing Cloud data extension in order to store the data in Marketing Cloud. Select any of the following optional settings so your developer can use the data in the Journey for this campaign. For the data from the options you select to be available in Journey Builder, create the fields in the Marketing Cloud Data Extension.")
```

2022-03-08 20:04 UTC, nriserEG commented on journey-builder/template.ts
> +    @headerSubtitle("After you select a recipe, create a Recommendations field in the event data extension in Marketing Cloud. This action allows you to add a Recommendations block to an email in Mar
```suggestion
    @headerSubtitle("After you select a recipe, create a Recommendations field in the event data extension in Marketing Cloud. Doing so allows you to add a Recommendations block to an email in Marketing Cloud.")
```

2022-03-08 20:08 UTC, nriserEG commented on journey-builder/template.ts
> +    @subtitle("After you select a recipe, create an Additional_Recommendations field in the event data extension in Marketing Cloud. This action allows you to add an Additional Recommendations block
```suggestion
    @subtitle("After you select a recipe, create an Additional_Recommendations field in the event data extension in Marketing Cloud. Doing so allows you to add an Additional Recommendations block to an email in Marketing Cloud.")
```

2022-03-08 20:11 UTC, nriserEG commented on journey-builder/template.ts
> +    @headerSubtitle("After you make your selections, create a field for each user attribute in the event data extension in Marketing Cloud. Data extension field names must match user attribute names.
```suggestion
    @headerSubtitle("After you select user attributes, create a field for each user attribute in the event data extension in Marketing Cloud. Data extension field names must match user attribute names.")
```

2022-03-08 21:22 UTC, nriserEG requested changes

2022-03-08 21:22 UTC, nriserEG commented on journey-builder-triggers/template.ts
> +            .map(item => item.toFlatJSON(JourneyBuilderTriggersUtils.defaultCatalogObjectAttributes, JourneyBuilderTriggersUtils.isCatalogLocalized ? locale : null));
we have a standard we follow for global templates where we break long lines to under 120 characters to improve readability
```suggestion
            .map(item => item.toFlatJSON(
                JourneyBuilderTriggersUtils.defaultCatalogObjectAttributes, 
                JourneyBuilderTriggersUtils.isCatalogLocalized ? locale : null
            ));
```

2022-03-08 21:22 UTC, nriserEG commented on journey-builder-triggers/template.ts
> +            return user.segmentMembership.filter(sm => selectedSegments.includes(sm.segmentId)).map(sm => sm.segmentName).join(",");
broke up long line
```suggestion
            return user.segmentMembership
                .filter(sm => selectedSegments.includes(sm.segmentId))
                .map(sm => sm.segmentName).join(",");
```

2022-03-08 21:22 UTC, nriserEG commented on journey-builder-triggers/template.ts
> +                        });
broke up long line
```suggestion
                        Object.keys(trigger.itemIdsByType).forEach(catalogObject => {
                            items.push(...JourneyBuilderTriggersUtils.getFlatItems(
                                context, catalogObject, trigger.itemIdsByType[catalogObject]
                            ));
                        });
```

2022-03-08 21:22 UTC, nriserEG commented on journey-builder-triggers/template.ts
> +    @headerSubtitle("After you select user attributes, create a field for each user attribute in the event data extension in Marketing Cloud. Data extension field names must match user attribute name
broke up long line
```suggestion
    @headerSubtitle(`After you select user attributes, create a field for each user attribute in the event data
        extension in Marketing Cloud. Data extension field names must match user attribute names.`)
```

2022-03-08 21:22 UTC, nriserEG commented on journey-builder-triggers/template.ts
> +    @headerSubtitle("After you select a recipe, create a Recommendations field in the event data extension in Marketing Cloud. Doing so allows you to add a Recommendations block to an email in Market
broke up long line
```suggestion
    @headerSubtitle(`After you select a recipe, create a Recommendations field in the event data extension in
        Marketing Cloud. Doing so allows you to add a Recommendations block to an email in Marketing Cloud.`)
```

2022-03-08 21:22 UTC, nriserEG commented on journey-builder-triggers/template.ts
> +    @subtitle("After you select a recipe, create an Additional_Recommendations field in the event data extension in Marketing Cloud. Doing so allows you to add an Additional Recommendations block to
broke up long line
```suggestion
    @subtitle(`After you select a recipe, create an Additional_Recommendations field in the event data extension in
        Marketing Cloud. Doing so allows you to add an Additional Recommendations block to an email in Marketing Cloud.`)
```

2022-03-08 21:22 UTC, nriserEG commented on journey-builder-triggers/template.ts
> +    @subtitle("After you select segments, create an Additional_Segment field in the event data extension in Marketing Cloud.")
broke up long line
```suggestion
    @subtitle(`After you select segments, create an Additional_Segment field in the event data extension in
        Marketing Cloud.`)
```

2022-03-08 21:22 UTC, nriserEG commented on journey-builder-triggers/template.ts
> +    @headerSubtitle("By default, the trigger includes the ContactKey and Trigger_Type fields. Depending on the trigger type, it could also include Trigger_Segment, Trigger_Action, and Trigger_Catalog
broke up long line
```suggestion
    @headerSubtitle(`By default, the trigger includes the ContactKey and Trigger_Type fields. Depending on the
        trigger type, it could also include Trigger_Segment, Trigger_Action, and Trigger_Catalog_Items fields.
        Create these fields in your Marketing Cloud data extension in order to store the data in Marketing Cloud.
        Select any of the following optional settings so your developer can use the data in the Journey for this
        campaign. For the data from the options you select to be available in Journey Builder, create the fields
        in the Marketing Cloud Data Extension.`)
```

2022-03-08 21:22 UTC, nriserEG commented on journey-builder-triggers/template.ts
> +            result["Additional_Recommendations"] = JourneyBuilderTriggersUtils.getRecommendations(this.additionalRecipe, context);
broke up long line
```suggestion
            result["Additional_Recommendations"] =
                JourneyBuilderTriggersUtils.getRecommendations(this.additionalRecipe, context);
```

2022-03-08 21:30 UTC, theKevinRobertsExperience commented on journey-builder-triggers/template.ts
> +                    if(trigger.itemIdsByType){
Good catch on these. I went through and added additional spacing to follow standards elsewhere but missed these ones.

2022-03-08 21:50 UTC, amaskiellEG requested changes
Left some minor comments but one thing I think we should discuss and potentially change before approving is the empty `catch` blocks.

Do we truly want to do nothing if there's a thrown exception? It seems like _some_ kind of logging might be helpful or even just returning a default value.

2022-03-08 21:50 UTC, amaskiellEG commented on journey-builder-triggers/template.ts
> +    static maxRecommendations = 8;
minor: maybe change the format to follow the convention for constants?

```suggestion
    static DEFAULT_CATALOG_OBJECT = "Product";
    static DEFAULT_CATALOG_OBJECT_ATTRIBUTES = ["id", "name", "imageUrl", "url", "price"];
    static MAX_RECOMMENDATIONS = 8;
```

2022-03-08 21:50 UTC, amaskiellEG commented on journey-builder-triggers/template.ts
> +        };
minor: would `triggerContext` ever contain the keys `"Campaign"` and/or `"Experience"`? And if so and if we want the keys from `context` to take preference, then this should be:

```suggestion
        const result = {
            ...triggerContext,
            "Campaign": context.campaignId,
            "Experience": context.experienceId,
        };
```

2022-03-08 21:50 UTC, amaskiellEG commented on journey-builder-triggers/template.ts
> +        return JSON.stringify(result);
Why are we only catching one possible exception and not another?

It seems like we're not potentially catching the second use of `stringify` because `result` would be an empty array but I'd almost rather see this instead:

```suggestion
            try {
                if (recipeConfig?.recipe?.id) {
                        const recs = recommend(context, recipeConfig).map(i => i.id);
                        result = JourneyBuilderTriggersUtils.getFlatItems(context, recipeConfig.itemType, recs);
                }
            } catch (ex) {
                return JSON.stringify([]);
            }
        }

        return JSON.stringify(result);
```

2022-03-08 21:56 UTC, amaskiellEG commented on journey-builder-triggers/template.ts
> +            .map(item => item.toFlatJSON(JourneyBuilderTriggersUtils.defaultCatalogObjectAttributes, JourneyBuilderTriggersUtils.isCatalogLocalized ? locale : null));
@nriserEG didn't we also make a call about always including parens for arguments in callbacks? Like
```js
.map((item) => item.toFlatJSON(
```
instead of
```js
.map(item => item.toFlatJSON(
```

_Aside: we should probably write some of these standards down somewhere or add a linter to enforce them 😅 _

2022-03-08 22:00 UTC, theKevinRobertsExperience commented on journey-builder-triggers/template.ts
> +        };
This shouldn't be the case. `triggerContext` is built through `getTriggerContext` which statically builds an object of `Trigger_Type` and optionally `Trigger_Segment`, `Trigger_Action` or `Trigger_Catalog_Items` based on the trigger type.

2022-03-08 22:12 UTC, theKevinRobertsExperience commented on journey-builder-triggers/template.ts
> +        return JSON.stringify(result);
We should just be returning a default value in all cases where there is a potential exception/issue.

2022-03-08 23:01 UTC, nriserEG commented on journey-builder-triggers/template.ts
> +            .map(item => item.toFlatJSON(JourneyBuilderTriggersUtils.defaultCatalogObjectAttributes, JourneyBuilderTriggersUtils.isCatalogLocalized ? locale : null));
yeah I think you're right

2022-03-09 01:27 UTC, nriserEG requested changes

2022-03-09 19:18 UTC, nriserEG approved these changes
Couldn't test on eng8 to confirm the Trigger_X fields without having proper MC access, but I was able to confirm the return of the other fields (User Attributes, Recommendations, Additional Recommendations, and User Segments) for my user using this [ServerSide campaign](https://eng8.devergage.com/ui/new-app/#/dataset/engage/campaigns/edit/FNFDf). See return below: 

```json
{
    "id": "6228f9cb7851c62a55dbd8c9",
    "campaignResponses": [
        {
            "type": "ng",
            "campaignId": "FNFDf",
            "campaignName": "Test Journey Builder Template in ServerSide Campaign",
            "campaignType": "ServerSide",
            "experienceId": "JsQUq",
            "experienceName": "Experience 1",
            "experienceSourceCode": "",
            "state": "Published",
            "campaignJavascriptContent": null,
            "userGroup": "Default",
            "templateNames": [
                "Journey Builder template"
            ],
            "payload": {
                "FirstName": "Nikki",
                "Segments": "Visited in Last Day,Decimal greater than 0",
                "LoyaltyPoints": "350",
                "kr-test": "",
                "experience": "JsQUq",
                "Recommendations": "[{\"price\":130,\"imageUrl\":\"https://www.northerntrailoutfitters.com/on/demandware.static/-/Sites-nto-apparel/default/dwfdd3a1d0/images/large/2050188ADH-0.jpg\",\"name\":\"Women's Endurus Tr\",\"id\":\"2050188\",\"url\":\"https://www.northerntrailoutfitters.com/default/women%27s-endurus-tr-2050188ADH.html\"},{\"price\":140,\"imageUrl\":\"https://www.northerntrailoutfitters.com/on/demandware.static/-/Sites-nto-apparel/default/dw0dec912f/images/large/2050078ARI-0.jpg\",\"name\":\"Women's Shellista Mid Boots\",\"id\":\"2050078\",\"url\":\"https://www.northerntrailoutfitters.com/default/women%E2%80%99s-shellista-mid-boots-2050078ARI.html\"},{\"price\":489,\"imageUrl\":\"https://www.northerntrailoutfitters.com/on/demandware.static/-/Sites-nto-gear/default/dw08a970f8/images/large/4070328AKH-0.jpg\",\"name\":\"Alpine Guide 3\",\"id\":\"4070328\",\"url\":\"https://www.northerntrailoutfitters.com/default/alpine-guide-3-4070328AKH.html\"},{\"price\":359.95,\"imageUrl\":\"https://www.northerntrailoutfitters.com/on/demandware.static/-/Sites-nto-gear/default/dwe5fc16e1/images/large/4070085AKK-0.jpg\",\"name\":\"Mica Fl 2\",\"id\":\"4070085\",\"url\":\"https://www.northerntrailoutfitters.com/default/mica-fl-2-4070085AKK.html\"},{\"price\":75,\"imageUrl\":\"https://www.northerntrailoutfitters.com/on/demandware.static/-/Sites-nto-apparel/default/dwffa0a3a8/images/large/1011060A0L-0.jpg\",\"name\":\"Men's Novelty Anorak\",\"id\":\"1011060\",\"url\":\"https://www.northerntrailoutfitters.com/default/men%E2%80%99s-novelty-anorak-1011060A0L.html\"},{\"price\":10,\"imageUrl\":\"https://www.northerntrailoutfitters.com/on/demandware.static/-/Sites-nto-gear/default/dw1b884399/images/large/5123403AS5-0.jpg\",\"name\":\"Lezyne Flow SL Water Bottle Cage - Right\",\"id\":\"5123403\",\"url\":\"https://www.northerntrailoutfitters.com/default/lezyne-flow-sl-water-bottle-cage---right-5123403AS5.html\"},{\"price\":229.95,\"imageUrl\":\"https://www.northerntrailoutfitters.com/on/demandware.static/-/Sites-nto-gear/default/dwca04cc66/images/large/4070101AN9-0.jpg\",\"name\":\"Homestead Roomy 2\",\"id\":\"4070101\",\"url\":\"https://www.northerntrailoutfitters.com/default/homestead-roomy-2-4070101AN9.html\"},{\"price\":285,\"imageUrl\":\"https://www.northerntrailoutfitters.com/on/demandware.static/-/Sites-nto-gear/default/dwdddb62a7/images/large/5132955A6Q-0.jpg\",\"name\":\"Troy Lee Designs Stage MIPS Bike Helmet\",\"id\":\"5132955\",\"url\":\"https://www.northerntrailoutfitters.com/default/troy-lee-designs-stage-mips-bike-helmet-5132955A6Q.html\"}]",
                "Additional_Recommendations": "[{\"price\":140,\"imageUrl\":\"https://www.northerntrailoutfitters.com/on/demandware.static/-/Sites-nto-apparel/default/dw0dec912f/images/large/2050078ARI-0.jpg\",\"name\":\"Women's Shellista Mid Boots\",\"id\":\"2050078\",\"url\":\"https://www.northerntrailoutfitters.com/default/women%E2%80%99s-shellista-mid-boots-2050078ARI.html\"},{\"price\":40,\"imageUrl\":\"https://www.northerntrailoutfitters.com/on/demandware.static/-/Sites-nto-apparel/default/dw58a076b7/images/large/2030173AC8-0.jpg\",\"name\":\"Women's Aphrodite 2.0 Shorts\",\"id\":\"2030173\",\"url\":\"https://www.northerntrailoutfitters.com/default/women%27s-aphrodite-2.0-shorts-2030173AC8.html\"},{\"price\":50,\"imageUrl\":\"https://www.northerntrailoutfitters.com/on/demandware.static/-/Sites-nto-apparel/default/dwecc77ef3/images/large/2030172AY7-0.jpg\",\"name\":\"Women's Aphrodite 2.0 Capris\",\"id\":\"2030172\",\"url\":\"https://www.northerntrailoutfitters.com/default/women%27s-aphrodite-2.0-capris-2030172AY7.html\"},{\"price\":120,\"imageUrl\":\"https://www.northerntrailoutfitters.com/on/demandware.static/-/Sites-nto-apparel/default/dw55dec89a/images/large/2050937BEQ-0.jpg\",\"name\":\"Women's Vals Wp Hiking Boot\",\"id\":\"2050937\",\"url\":\"https://www.northerntrailoutfitters.com/default/women%E2%80%99s-vals-wp-hiking-boot-2050937BEQ.html\"},{\"price\":90,\"imageUrl\":\"https://www.northerntrailoutfitters.com/on/demandware.static/-/Sites-nto-apparel/default/dwf9d82181/images/large/2050857ATT-0.jpg\",\"name\":\"Women's Rovereto Running Shoes\",\"id\":\"2050857\",\"url\":\"https://www.northerntrailoutfitters.com/default/women%E2%80%99s-rovereto-running-shoes-2050857ATT.html\"},{\"price\":65,\"imageUrl\":\"https://www.northerntrailoutfitters.com/on/demandware.static/-/Sites-nto-apparel/default/dwf5e945e8/images/large/2021006AC8-0.jpg\",\"name\":\"Women's Glacier Alpine Pullover\",\"id\":\"2021006\",\"url\":\"https://www.northerntrailoutfitters.com/default/women%E2%80%99s-glacier-alpine-pullover-2021006AC8.html\"},{\"price\":850,\"imageUrl\":\"https://www.northerntrailoutfitters.com/on/demandware.static/-/Sites-nto-gear/default/dw78b33543/images/large/5112812AN1-0.jpg\",\"name\":\"Salsa Journeyman Claris 650 Bike\",\"id\":\"5112812\",\"url\":\"https://www.northerntrailoutfitters.com/default/salsa-journeyman-claris-650-bike-5112812AN1.html\"},{\"price\":100,\"imageUrl\":\"https://www.northerntrailoutfitters.com/on/demandware.static/-/Sites-nto-apparel/default/dw9a18b337/images/large/2050859A37-0.jpg\",\"name\":\"Women's Corvara Running Shoes\",\"id\":\"2050859\",\"url\":\"https://www.northerntrailoutfitters.com/default/women%E2%80%99s-corvara-running-shoes-2050859A37.html\"}]",
                "templateConfig": {
                    "includeAdditionalRecommendations": true,
                    "includeSegments": true,
                    "attributes": [
                        {
                            "id": "Decimal",
                            "label": "Decimal",
                            "type": "Decimal"
                        },
                        {
                            "id": "kr-test",
                            "label": "kr-test",
                            "type": "String"
                        },
                        {
                            "id": "FirstName",
                            "label": "FirstName",
                            "type": "String"
                        },
                        {
                            "id": "LoyaltyPoints",
                            "label": "LoyaltyPoints",
                            "type": "Integer"
                        }
                    ],
                    "recipe": {
                        "id": "1bqSL",
                        "label": "Random Prodcuts"
                    },
                    "additionalRecipe": {
                        "id": "Sy4it",
                        "label": "Trending Products"
                    },
                    "segments": [
                        {
                            "id": "8j7y6",
                            "label": "KR TEST"
              [...]

2022-03-09 19:26 UTC, amaskiellEG approved these changes
This looks good to me 🙂 

I still think it's weird to have an empty `catch` block in `getTriggerContext` (and a return type of `any`?) but both of those could be addressed in a later update.

2022-03-09 22:35 UTC, merged