@W-10745698@ Feature | Add Salesforce Chatbot Global Template
evergage/evergage-global-templates pull request #41
Opened 2022-03-25 19:36 UTC by jsantacruzEG

# Description

This PR adds the Salesforce Chatbot template which interacts with the chatbot that is embedded on a client's website. It is based on a design from [Juliano Polito](https://bitbucket.org/julianopolito/autoopen-sdochat/src/master/ ) (SF POP team) The template requires that the client already has the chatbot installed on their website. It does not use any html or css. There are two websites that run the chatbot that can be used as a point of reference: [northerntrailoutfitters.com]([https://www.northerntrailoutfitters.com/default/homepage](https://www.northerntrailoutfitters.com/default/homepage?test=fallbackArm)) and [salesforce.com](https://www.salesforce.com/)
 
## Related Issues/Tickets

GUS: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000rQyrrYAC/view

## How to test
_Note: I experienced many issues in testing mode with this template. Kevin Roberts is aware of a potential bug on production that is impacting campaigns and testing with test params in the URL as well as saving campaigns with errors and publishing._

In the campaign there are 3 experiences:
Scroll Depth:
https://www.northerntrailoutfitters.com/default/homepage?evergageTestMessages=Fqv6Z
Time on Page:
https://www.northerntrailoutfitters.com/default/homepage?evergageTestMessages=82A4o
Inactivity:
https://www.northerntrailoutfitters.com/default/homepage?evergageTestMessages=KMQVt

Please test them to see if they fire correctly and that stats are properly collected.

#### Template:
- You can view the demo template in eng7:jsantacruztest, **template name: Salesforce Chatbot**.
If you need access to eng7 please let me know and I can create an account for you.
#### Campaign:
- You can view the demo campaign using this template in account:dataset, **campaign name: [Salesforce Chatbot](https://eng7.devergage.com/ui/new-app/#/dataset/jsantacruztest/campaigns/edit/8w8DD)**
Note: you will need to force the SDK using this URL: [(https://eng7.devergage.com/beacon/eng7/jsantacruztest/scripts/evergage.min.js)](https://eng7.devergage.com/beacon/eng7/jsantacruztest/scripts/evergage.min.js)

### Things to check for:
* **Functionality**: Do the rules properly control the behavior of the chatbot?
* **Template-specific documentation**: Is there sufficient information for a Template Developer to use the Global Template and customize it for their own use?
* **Campaign stats tracking:** Do impression stats and click stats fire for both the Control and Test experience?

2022-03-28 20:38 UTC, dchouEG requested changes
After testing, I ran into some errors with the campaigns not being able to save. I was able to trace it back to the option to save scroll depth triggering an error in this code: analytics/excavator/src/main/java/com/apptegic/excavate/persistence/mongo/codec/BsonWritingJsonGenerator.java line 67. The problem seems to be the value "0.5" It looks like we also have another Global Template that utilizes this logic and is also triggering the same error with serialization. 

I think we may need to remove that option. After removing the scrollig depth option, the errors went away when trying to save.

2022-03-28 20:38 UTC, dchouEG commented on salesforce-chatbot/client.js
> +    }
It looks like handleChatBot is not using the context or template here. We can remove these parameters and wherever it is being called, remove them there as well. The function looks like it triggers the chatbox open, something like `openChatbot` or `triggerChatbot` would be a better name here for this function.

2022-03-28 20:38 UTC, dchouEG commented on salesforce-chatbot/client.js
> +                        handleChatbot({ context, template });
see first comment above and everywhere else this function is being called.

2022-03-28 20:38 UTC, dchouEG commented on salesforce-chatbot/client.js
> +                    .then((event) => {
event is not used anywhere
```suggestion
                    .then(() => {
```

2022-03-28 20:38 UTC, dchouEG commented on salesforce-chatbot/client.js
> +                    .then((event) => {
here as well
```suggestion
                    .then(() => {
```

2022-03-28 20:38 UTC, dchouEG commented on salesforce-chatbot/template.hbs
> +    This global template interacts with the Salesforce Chatbot that is embedded on your website.
Sentence here can be updated to indicate this global template triggers the Salesforce Chatbox

2022-03-28 20:38 UTC, dchouEG commented on salesforce-chatbot/template.hbs
> +
Provide a link to the Salesforce Chatbox dev page just to make sure they are aware that this chatbox is part of the requirements.

2022-03-29 13:22 UTC, dchouEG commented on salesforce-chatbot/client.js
> +    function apply(context, template) {
The apply function should be refactored. When using `handleTriggerEvent` it returns a promise with .then chained in the end, but if you scroll up to `handleTriggerEvent` the function is already chaining the `.then`, also `template` is not used so it shouldn't be passed down in the function if you intend to keep the function.

2022-03-30 17:10 UTC, dchouEG commented on salesforce-chatbot/client.js
> +                });
This whole function doesn't get called so Dismissal and Clicks aren't being recorded. This whole block can be abstracted out into its own function and used within the `handleTriggerEvent` function above, since it is the same code, just call it in the final .then() in the handleTriggerEvent to make sure it gets called.

2022-04-01 17:34 UTC, dchouEG approved these changes

2022-04-18 15:11 UTC, amaskiellEG commented
Closing this in favor of #43

2022-04-18 15:13 UTC, amaskiellEG commented
Closing this in favor of #43

2022-04-18 15:13 UTC, closed without merging